<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DescriptionUnitsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('description_units')->insert([

            ['cat_description_id' => 1, 'cat_unit_id' => 1],
            ['cat_description_id' => 2, 'cat_unit_id' => 2],
            ['cat_description_id' => 3, 'cat_unit_id' => 2],
            ['cat_description_id' => 4, 'cat_unit_id' => 2],

            ['cat_description_id' => 5, 'cat_unit_id' => 3],
            ['cat_description_id' => 6, 'cat_unit_id' => 2],
            ['cat_description_id' => 7, 'cat_unit_id' => 1],
            ['cat_description_id' => 8, 'cat_unit_id' => 2],
            ['cat_description_id' => 9, 'cat_unit_id' => 2],
            ['cat_description_id' => 10, 'cat_unit_id' => 2],
            ['cat_description_id' => 11, 'cat_unit_id' => 2],

            ['cat_description_id' => 12, 'cat_unit_id' => 4],
            ['cat_description_id' => 13, 'cat_unit_id' => 4],
            ['cat_description_id' => 14, 'cat_unit_id' => 4],
            ['cat_description_id' => 15, 'cat_unit_id' => 4],
            ['cat_description_id' => 16, 'cat_unit_id' => 4],
            ['cat_description_id' => 17, 'cat_unit_id' => 4],
            ['cat_description_id' => 18, 'cat_unit_id' => 4],

            ['cat_description_id' => 19, 'cat_unit_id' => 3],
            ['cat_description_id' => 20, 'cat_unit_id' => 3],
            ['cat_description_id' => 21, 'cat_unit_id' => 3],
            ['cat_description_id' => 22, 'cat_unit_id' => 3],
            ['cat_description_id' => 23, 'cat_unit_id' => 3],
            ['cat_description_id' => 24, 'cat_unit_id' => 3],
            ['cat_description_id' => 25, 'cat_unit_id' => 3],
            ['cat_description_id' => 26, 'cat_unit_id' => 3],
            ['cat_description_id' => 27, 'cat_unit_id' => 3],
            ['cat_description_id' => 28, 'cat_unit_id' => 3],
            ['cat_description_id' => 29, 'cat_unit_id' => 5],
            ['cat_description_id' => 30, 'cat_unit_id' => 3],
            ['cat_description_id' => 31, 'cat_unit_id' => 3],
            ['cat_description_id' => 32, 'cat_unit_id' => 3],
            ['cat_description_id' => 33, 'cat_unit_id' => 3],

            ['cat_description_id' => 34, 'cat_unit_id' => 4],
            ['cat_description_id' => 35, 'cat_unit_id' => 4],
            ['cat_description_id' => 36, 'cat_unit_id' => 4],
            ['cat_description_id' => 37, 'cat_unit_id' => 4],
            ['cat_description_id' => 38, 'cat_unit_id' => 4],
            ['cat_description_id' => 39, 'cat_unit_id' => 4],
            ['cat_description_id' => 40, 'cat_unit_id' => 4],
            ['cat_description_id' => 41, 'cat_unit_id' => 4],
            ['cat_description_id' => 42, 'cat_unit_id' => 4],
            ['cat_description_id' => 43, 'cat_unit_id' => 4],
            ['cat_description_id' => 44, 'cat_unit_id' => 4],
            ['cat_description_id' => 45, 'cat_unit_id' => 4],
            ['cat_description_id' => 46, 'cat_unit_id' => 4],
            ['cat_description_id' => 47, 'cat_unit_id' => 4],

            ['cat_description_id' => 48, 'cat_unit_id' => 6],
            ['cat_description_id' => 49, 'cat_unit_id' => 6],
            ['cat_description_id' => 52, 'cat_unit_id' => 6],
            ['cat_description_id' => 53, 'cat_unit_id' => 3],
            ['cat_description_id' => 54, 'cat_unit_id' => 6],
            ['cat_description_id' => 55, 'cat_unit_id' => 6],
            ['cat_description_id' => 56, 'cat_unit_id' => 6],
            ['cat_description_id' => 57, 'cat_unit_id' => 6],
            ['cat_description_id' => 58, 'cat_unit_id' => 6],
            ['cat_description_id' => 59, 'cat_unit_id' => 6],
            ['cat_description_id' => 60, 'cat_unit_id' => 6],
            ['cat_description_id' => 61, 'cat_unit_id' => 6],
            ['cat_description_id' => 62, 'cat_unit_id' => 6],
            ['cat_description_id' => 63, 'cat_unit_id' => 6],
            ['cat_description_id' => 64, 'cat_unit_id' => 6],
            ['cat_description_id' => 65, 'cat_unit_id' => 6],

            ['cat_description_id' => 66, 'cat_unit_id' => 6],
            ['cat_description_id' => 67, 'cat_unit_id' => 6],
            ['cat_description_id' => 68, 'cat_unit_id' => 6],
            ['cat_description_id' => 69, 'cat_unit_id' => 6],
            ['cat_description_id' => 70, 'cat_unit_id' => 6],
            ['cat_description_id' => 71, 'cat_unit_id' => 7],
            ['cat_description_id' => 72, 'cat_unit_id' => 6],

            ['cat_description_id' => 73, 'cat_unit_id' => 8],
            ['cat_description_id' => 74, 'cat_unit_id' => 8],
            ['cat_description_id' => 75, 'cat_unit_id' => 8],
            ['cat_description_id' => 76, 'cat_unit_id' => 8],
            ['cat_description_id' => 77, 'cat_unit_id' => 8],
            ['cat_description_id' => 78, 'cat_unit_id' => 9],
            ['cat_description_id' => 79, 'cat_unit_id' => 9],
            ['cat_description_id' => 80, 'cat_unit_id' => 9],
            ['cat_description_id' => 81, 'cat_unit_id' => 9],
            ['cat_description_id' => 82, 'cat_unit_id' => 8],

            ['cat_description_id' => 83, 'cat_unit_id' => 10],
            ['cat_description_id' => 84, 'cat_unit_id' => 10],
            ['cat_description_id' => 85, 'cat_unit_id' => 10],
            ['cat_description_id' => 86, 'cat_unit_id' => 10],
            ['cat_description_id' => 87, 'cat_unit_id' => 10],
            ['cat_description_id' => 88, 'cat_unit_id' => 11],
            ['cat_description_id' => 88, 'cat_unit_id' => 12],

            ['cat_description_id' => 89, 'cat_unit_id' => 13],
            ['cat_description_id' => 89, 'cat_unit_id' => 4],
            ['cat_description_id' => 90, 'cat_unit_id' => 14],
            ['cat_description_id' => 91, 'cat_unit_id' => 14],
            ['cat_description_id' => 92, 'cat_unit_id' => 14],

            ['cat_description_id' => 93, 'cat_unit_id' => 11],
            ['cat_description_id' => 93, 'cat_unit_id' => 12],
            ['cat_description_id' => 94, 'cat_unit_id' => 4],
            ['cat_description_id' => 95, 'cat_unit_id' => 11],
            ['cat_description_id' => 95, 'cat_unit_id' => 12],

            ['cat_description_id' => 96, 'cat_unit_id' => 15],
            ['cat_description_id' => 97, 'cat_unit_id' => 15],
            ['cat_description_id' => 98, 'cat_unit_id' => 15],
            ['cat_description_id' => 99, 'cat_unit_id' => 15],

            ['cat_description_id' => 100, 'cat_unit_id' => null],
            ['cat_description_id' => 101, 'cat_unit_id' => 16],
            ['cat_description_id' => 101, 'cat_unit_id' => 17],
            ['cat_description_id' => 101, 'cat_unit_id' => 18],
            ['cat_description_id' => 101, 'cat_unit_id' => 19],
            ['cat_description_id' => 102, 'cat_unit_id' => 7],
            ['cat_description_id' => 103, 'cat_unit_id' => 20],
            ['cat_description_id' => 104, 'cat_unit_id' => 19],
            ['cat_description_id' => 105, 'cat_unit_id' => 19],
            ['cat_description_id' => 106, 'cat_unit_id' => 1],
            ['cat_description_id' => 107, 'cat_unit_id' => 1],
            ['cat_description_id' => 107, 'cat_unit_id' => 16],
            ['cat_description_id' => 107, 'cat_unit_id' => 17],
            ['cat_description_id' => 108, 'cat_unit_id' => 18],
            ['cat_description_id' => 109, 'cat_unit_id' => 1],
            ['cat_description_id' => 110, 'cat_unit_id' => 1],
            ['cat_description_id' => 111, 'cat_unit_id' => 21],
            ['cat_description_id' => 112, 'cat_unit_id' => 1],
            ['cat_description_id' => 113, 'cat_unit_id' => 21],
            ['cat_description_id' => 114, 'cat_unit_id' => 20],
            ['cat_description_id' => 115, 'cat_unit_id' => 19],
            ['cat_description_id' => 115, 'cat_unit_id' => 22],
            ['cat_description_id' => 116, 'cat_unit_id' => 23],
            ['cat_description_id' => 116, 'cat_unit_id' => 16],
            ['cat_description_id' => 117, 'cat_unit_id' => 18],
            ['cat_description_id' => 118, 'cat_unit_id' => 11],
            ['cat_description_id' => 119, 'cat_unit_id' => 3],
            ['cat_description_id' => 120, 'cat_unit_id' => 3],
            ['cat_description_id' => 121, 'cat_unit_id' => 3],

            ['cat_description_id' => 122, 'cat_unit_id' => 24],
   //         ['cat_description_id' => 123, 'cat_unit_id' => null],
            ['cat_description_id' => 124, 'cat_unit_id' => 1],
            ['cat_description_id' => 125, 'cat_unit_id' => 25],
   //         ['cat_description_id' => 126, 'cat_unit_id' => null],
            ['cat_description_id' => 127, 'cat_unit_id' => 26],
            ['cat_description_id' => 128, 'cat_unit_id' => 27],
            ['cat_description_id' => 129, 'cat_unit_id' => 28],
            ['cat_description_id' => 130, 'cat_unit_id' => 1],
            ['cat_description_id' => 131, 'cat_unit_id' => 16],
            ['cat_description_id' => 131, 'cat_unit_id' => 17],
            ['cat_description_id' => 131, 'cat_unit_id' => 18],
            ['cat_description_id' => 132, 'cat_unit_id' => 7],
            ['cat_description_id' => 133, 'cat_unit_id' => 29],
            ['cat_description_id' => 134, 'cat_unit_id' => 7],

            ['cat_description_id' => 135, 'cat_unit_id' => 1],
            ['cat_description_id' => 136, 'cat_unit_id' => 30],
            ['cat_description_id' => 137, 'cat_unit_id' => 16],
            ['cat_description_id' => 137, 'cat_unit_id' => 17],
            ['cat_description_id' => 137, 'cat_unit_id' => 18],
            ['cat_description_id' => 137, 'cat_unit_id' => 19],
            ['cat_description_id' => 138, 'cat_unit_id' => 24],
            ['cat_description_id' => 138, 'cat_unit_id' => 31],
            ['cat_description_id' => 139, 'cat_unit_id' => 32],
            ['cat_description_id' => 139, 'cat_unit_id' => 33],
            ['cat_description_id' => 140, 'cat_unit_id' => 24],
            ['cat_description_id' => 140, 'cat_unit_id' => 31],
            ['cat_description_id' => 141, 'cat_unit_id' => 4],
            ['cat_description_id' => 142, 'cat_unit_id' => 1],
            ['cat_description_id' => 143, 'cat_unit_id' => 30],
            ['cat_description_id' => 144, 'cat_unit_id' => 1],
            ['cat_description_id' => 145, 'cat_unit_id' => 4],
            ['cat_description_id' => 146, 'cat_unit_id' => 30],
            ['cat_description_id' => 147, 'cat_unit_id' => 32],
            ['cat_description_id' => 148, 'cat_unit_id' => 32],
            ['cat_description_id' => 149, 'cat_unit_id' => 32],
            ['cat_description_id' => 150, 'cat_unit_id' => 32],

        ]);
    }
}
