<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatAdministrativeUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_administrative_units')->insert([
            ['id' => 1, 'name' => 'Dirección General del Acervo Histórico Diplomático', 'determinant' => 'DGAHD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 2, 'name' => 'Consultoría Jurídica', 'determinant' => 'CJA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 3, 'name' => 'Dirección General de Asuntos Jurídicos', 'determinant' => 'ASJ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 4, 'name' => 'Dirección General del Servicio Exterior y de Recursos Humanos', 'determinant' => 'DSE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 5, 'name' => 'Dirección General de Programación, Organización y Presupuesto', 'determinant' => 'POP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 6, 'name' => 'Sindicato Nacional de Trabajadores de la Secretaría de Relaciones Exteriores', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 7, 'name' => 'Dirección General de Bienes Inmuebles y Recursos Materiales', 'determinant' => 'IRM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 8, 'name' => 'Dirección General de Protocolo', 'determinant' => 'PRO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 9, 'name' => 'Dirección General de Tecnologías de Información e Innovación', 'determinant' => 'TIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 10, 'name' => 'Dirección General de Acrvo Histórico Diplomático', 'determinant' => 'AHD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 11, 'name' => 'Dirección General de Comunicación Social', 'determinant' => 'DCS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 12, 'name' => 'Jefatura de la Oficina del Canciller', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 13, 'name' => 'Coordinación General de Asesores', 'determinant' => 'CGA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 14, 'name' => 'Coordinación de Asesores de Oficialía Mayor', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 15, 'name' => 'De aplicación general', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 16, 'name' => 'Unidad de Transparencia', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 17, 'name' => 'Dirección General para Asia-Pacifico', 'determinant' => 'DAP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 18, 'name' => 'Dirección General para Europa', 'determinant' => 'DGE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 19, 'name' => 'Dirección General para África y Medio Oriente', 'determinant' => 'AMO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 20, 'name' => 'Dirección General para América Latina y el Caribe', 'determinant' => 'ALC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 21, 'name' => 'Dirección General para América del Norte', 'determinant' => 'DAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 22, 'name' => 'Dirección General para Asuntos Espciales', 'determinant' => 'DAE', 'crated_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 23, 'name' => 'CILA Norte', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 24, 'name' => 'CILA Sur', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 25, 'name' => 'Dirección General de Servicios Consulares', 'determinant' => 'DSC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 26, 'name' => 'Dirección General de Derechos Humanos y Democracia', 'determinant' => 'DDH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 27, 'name' => 'Dirección General para la Organización de las Naciones Unidas', 'determinant' => 'DNU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 28, 'name' => 'Dirección General para Temas Globales', 'determinant' => 'TEL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 29, 'name' => 'Dirección General de Organismos y Mecanismos Regionales', 'determinant' => 'ORA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 30, 'name' => 'Dirección General de Vinculación con las Organizaciones de la Sociedad Civil', 'determinant' => 'VOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 31, 'name' => 'Dirección General de Protección a Mexicanos en el Exterior', 'determinant' => 'PME', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 32, 'name' => 'Representaciones de México en el exterior', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 33, 'name' => 'Dirección General de Delegaciones', 'determinant' => 'DGD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 34, 'name' => 'Delegaciones Locales y Foráneas', 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],


            //Unidades Administrativas que faltan....

            ['id' => 35, 'name' => 'Secretaría Particular', 'determinant' => 'SPR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 36, 'name' => 'Comisión de personal del servicio exterior mexicano', 'determinant' => 'DCP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 37, 'name' => 'Centro de enlace diplomático', 'determinant' => 'CED', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 38, 'name' => 'Dirección general de coordinación política', 'determinant' => 'DEP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 39, 'name' => 'Instituto Matias Romero', 'determinant' => 'IMR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 40, 'name' => 'Subsecretaría de relaciones exteriores', 'determinant' => 'SSRE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 41, 'name' => 'Subsecretaría para América del norte', 'determinant' => 'SSAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 42, 'name' => 'Instituto de los mexicanos en el exterior', 'determinant' => 'IME', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 43, 'name' => 'Sección mexicana de la comisión internacional de límites y aguas entre México y Estados Unidos', 'determinant' => 'CEU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 44, 'name' => 'Subsecretaría para América latina y el caribe', 'determinant' => 'SSAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 45, 'name' => 'Sección mexicana de la comisión internacional de límites y aguas entre México y Guatemala y entre México y Belice', 'determinant' => 'CGB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 46, 'name' => 'Subsecretaría para asuntos multilaterales y derechos humanos', 'determinant' => 'SSMH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 47, 'name' => 'Unidad de administración y finanzas', 'determinant' => 'UAF', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 48, 'name' => 'Agencia Mexicana de cooperación internacional para el desarrollo', 'determinant' => 'AMI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 49, 'name' => 'Dirección general de cooperación educativa y cultural', 'determinant' => 'CEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 50, 'name' => 'Dirección general de cooperación y promoción económica internacional', 'determinant' => 'PEI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 51, 'name' => 'Dirección general de cooperación y relaciones económicas bilaterales', 'determinant' => 'REB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 52, 'name' => 'Dirección general de cooperación técnica y científica', 'determinant' => 'CTC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 53, 'name' => 'Dirección general del proyecyo integración y desarrollo de Mesoamérica', 'determinant' => 'IDM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 54, 'name' => 'Dirección general de planeación y cooperación económica internacional', 'determinant' => 'PCI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Delegaciones Metropolitanas

            ['id' => 55, 'name' => 'Delegación Álvaro Obregón', 'determinant' => 'AOM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 56, 'name' => 'Delegación Benito Juárez', 'determinant' => 'BJM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 57, 'name' => 'Delegación Cuajimalpa de Morelos', 'determinant' => 'CUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 58, 'name' => 'Delegación Cuauhtemoc', 'determinant' => 'CUM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 59, 'name' => 'Delegación Gustavo A. Madero', 'determinant' => 'GAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 60, 'name' => 'Delegación Iztacalco', 'determinant' => 'IZT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 61, 'name' => 'Delegación Iztapalapa', 'determinant' => 'IZP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 62, 'name' => 'Delegación Miguel Hidalgo', 'determinant' => 'MHM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 63, 'name' => 'Delegación Naucalpan, Estado de México', 'determinant' => 'EMN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 64, 'name' => 'Delegación Tlalpan', 'determinant' => 'TLM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 65, 'name' => 'Delegación Venustiano Carranza', 'determinant' => 'VEM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 66, 'name' => 'Edificio Tlatelolco, Plaza Juárez', 'determinant' => 'TCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Delegaciones Foráneas

            ['id' => 67, 'name' => 'Delegación Acapulco, Guerrero', 'determinant' => 'ACP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 68, 'name' => 'Delegación Aguascalientes, Aguascalientes', 'determinant' => 'AGS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 69, 'name' => 'Delegación Campeche, Campeche', 'determinant' => 'CAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 70, 'name' => 'Delegación Cancún, Quintana Roo', 'determinant' => 'CUN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 71, 'name' => 'Delegación Chihuahua, Chihuahua', 'determinant' => 'CHH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 72, 'name' => 'Delegación Ciudad Juárez, Chihuahua', 'determinant' => 'CJU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 73, 'name' => 'Delegación Ciudad Victoria, Tamaulipas', 'determinant' => 'CVT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 74, 'name' => 'Delegación Colima, Colima', 'determinant' => 'DCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 75, 'name' => 'Delegación Cuernavaca, Morelos', 'determinant' => 'DMO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 76, 'name' => 'Delegación Culiacán, Sinaloa', 'determinant' => 'SIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 77, 'name' => 'Delegación Durango, Durango', 'determinant' => 'DUR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 78, 'name' => 'Delegación Guadalajara, Jalisco', 'determinant' => 'JAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 79, 'name' => 'Delegación Hermosillo, Sonora', 'determinant' => 'SON', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 80, 'name' => 'Delegación Jalapa, Veracruz', 'determinant' => 'VER', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 81, 'name' => 'Delegación La Paz, Baja California Sur', 'determinant' => 'BCS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 82, 'name' => 'Delegación León, Guanajuato', 'determinant' => 'LEO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 83, 'name' => 'Delegación Mérida, Yucatan', 'determinant' => 'YUC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 84, 'name' => 'Delegación Mexicali, Baja California', 'determinant' => 'BCN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 85, 'name' => 'Delegación Monterrey, Nuevo León', 'determinant' => 'NLE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 86, 'name' => 'Delegación Morelia, Michoacán', 'determinant' => 'MOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 87, 'name' => 'Delegación Oaxaca, Oaxaca', 'determinant' => 'OAX', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 88, 'name' => 'Delegación Pachuca, Hidalgo', 'determinant' => 'HGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 89, 'name' => 'Delegación Puebla, Puebla', 'determinant' => 'PUE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 90, 'name' => 'Delegación Querétaro, Querétaro', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 91, 'name' => 'Delegación San Luis Potosi, San Luis Potosi', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 92, 'name' => 'Delegación Tepic, Nayarit', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 93, 'name' => 'Delegación Tijuana, Baja California Norte', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 94, 'name' => 'Delegación Tlaxcala, Tlaxcala', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 95, 'name' => 'Delegación Toluca, Estado de México', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 96, 'name' => 'Delegación Torreón, Coahuila', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 97, 'name' => 'Delegación Tuxtla Gutierrez, Chiapas', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 98, 'name' => 'Delegación Villahermosa, Tabasco', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 99, 'name' => 'Delegación Zacatecas, Zacatecas', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Embajadas

            ['id' => 100, 'name' => 'Alemania, Embajada', 'determinant' => 'ALE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 101, 'name' => 'Arabia Saudita, Embajada', 'determinant' => 'ASA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 102, 'name' => 'Argelia, Embajada', 'determinant' => 'ARL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 103, 'name' => 'Argentina, Embajada', 'determinant' => 'ARG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 104, 'name' => 'Australia, Embajada', 'determinant' => 'AUS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 105, 'name' => 'Austria, Embajada', 'determinant' => 'AUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 106, 'name' => 'Azerbaiyan, Embajada', 'determinant' => 'AZE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 107, 'name' => 'Bélgica, Embajada', 'determinant' => 'BEL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 108, 'name' => 'Belize, Embajada', 'determinant' => 'BEE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 109, 'name' => 'Bolivia, Embajada', 'determinant' => 'BOL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 110, 'name' => 'Brasil, Embajada', 'determinant' => 'BRA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 111, 'name' => 'Canadá, Embajada', 'determinant' => 'CAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 112, 'name' => 'Chile, Embajada', 'determinant' => 'CHI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 113, 'name' => 'China, Embajada', 'determinant' => 'CHN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 114, 'name' => 'Colombia, Embajada', 'determinant' => 'COL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 115, 'name' => 'Corea, Embajada', 'determinant' => 'COR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 116, 'name' => 'Costa Rica, Embajada', 'determinant' => 'CRI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 117, 'name' => 'Cuba, Embajada', 'determinant' => 'CUB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 118, 'name' => 'Dinamarca, Embajada', 'determinant' => 'DIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 119, 'name' => 'Ecuador, Embajada', 'determinant' => 'ECU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 120, 'name' => 'Egipto, Embajada', 'determinant' => 'RAE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 121, 'name' => 'El Salvador, Embajada', 'determinant' => 'ESA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 122, 'name' => 'Emiratos Árabe Unidos, Embajada', 'determinant' => 'EAU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 123, 'name' => 'España, Embajada', 'determinant' => 'ESP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 124, 'name' => 'Estados Unidos, Embajada', 'determinant' => 'EUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 125, 'name' => 'Etiopia, Embajada', 'determinant' => 'ETI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 126, 'name' => 'Federación de Rusia, Embajada', 'determinant' => 'RUS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 127, 'name' => 'Filipinas, Embajada', 'determinant' => 'FIL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 128, 'name' => 'Finlandia, Embajada', 'determinant' => 'FIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 129, 'name' => 'Francia, Embajada', 'determinant' => 'FRA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 130, 'name' => 'Ghana, Embajada', 'determinant' => 'GHA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 131, 'name' => 'Grecia, Embajada', 'determinant' => 'GRE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 132, 'name' => 'Guatemala, Embajada', 'determinant' => 'GUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 133, 'name' => 'Guyana, Embajada', 'determinant' => 'GUY', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 134, 'name' => 'Haití, Embajada', 'determinant' => 'HAI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 135, 'name' => 'Honduras, Embajada', 'determinant' => 'HON', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 136, 'name' => 'Hungría, Embajada', 'determinant' => 'HUN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 137, 'name' => 'India, Embajada', 'determinant' => 'IND', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 138, 'name' => 'Indonesia, Embajada', 'determinant' => 'INO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 139, 'name' => 'Irán, Embajada', 'determinant' => 'IRN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 140, 'name' => 'Irlanda, Embajada', 'determinant' => 'IRL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 141, 'name' => 'Israel, Embajada', 'determinant' => 'ISR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 142, 'name' => 'Italia, Embajada', 'determinant' => 'ITA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 143, 'name' => 'Jamaica, Embajada', 'determinant' => 'JAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 144, 'name' => 'Japón, Embajada', 'determinant' => 'JAP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 145, 'name' => 'Jordania, Embajada', 'determinant' => 'JOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 146, 'name' => 'Kenia, Embajada', 'determinant' => 'KEN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 147, 'name' => 'Kuwait, Embajada', 'determinant' => 'KWT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 148, 'name' => 'Líbano, Embajada', 'determinant' => 'LIB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 149, 'name' => 'Malasia, Embajada', 'determinant' => 'MLS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 150, 'name' => 'Marruecos, Embajada', 'determinant' => 'MAR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 151, 'name' => 'Nicaragua, Embajada', 'determinant' => 'NIC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 152, 'name' => 'Nigeria, Embajada', 'determinant' => 'NIG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 153, 'name' => 'Noruega, Embajada', 'determinant' => 'NOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 154, 'name' => 'Nueva Zelanda, Embajada', 'determinant' => 'NZE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 155, 'name' => 'Países Bajos, Embajada', 'determinant' => 'PBA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 156, 'name' => 'Panamá, Embajada', 'determinant' => 'PAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 157, 'name' => 'Paraguay, Embajada', 'determinant' => 'PAY', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 158, 'name' => 'Perú, Embajada', 'determinant' => 'PER', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 159, 'name' => 'Polonia, Embajada', 'determinant' => 'POL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 160, 'name' => 'Portugal, Embajada', 'determinant' => 'POR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 161, 'name' => 'Qatar, Embajada', 'determinant' => 'QAT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 162, 'name' => 'Reino Unido de la Gran Bretaña e Irlanda del Norte, Embajada', 'determinant' => 'GBR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 163, 'name' => 'República Checa, Embajada', 'determinant' => 'CHE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 164, 'name' => 'República Dominicana, Embajada', 'determinant' => 'DOM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 165, 'name' => 'Rumania, Embajada', 'determinant' => 'RUM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 166, 'name' => 'Santa Lucia, Embajada', 'determinant' => 'LCA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 167, 'name' => 'Santa Sede, El Vaticano, Embajada', 'determinant' => 'VAT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 168, 'name' => 'Serbia, Embajada', 'determinant' => 'SEB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 169, 'name' => 'Singapur, Embajada', 'determinant' => 'SIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 170, 'name' => 'Sudáfrica, Embajada', 'determinant' => 'SUD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 171, 'name' => 'Suecia, Embajada', 'determinant' => 'SUE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 172, 'name' => 'Suiza, Embajada', 'determinant' => 'SUI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 173, 'name' => 'Tailandia, Embajada', 'determinant' => 'TAI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 174, 'name' => 'Trinidad y Tobago, Embajada', 'determinant' => 'TRT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 175, 'name' => 'Turquía, Embajada', 'determinant' => 'TUR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 176, 'name' => 'Ucrania, Embajada', 'determinant' => 'UCR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 177, 'name' => 'Uruguay, Embajada', 'determinant' => 'URU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 178, 'name' => 'Venezuela, Embajada', 'determinant' => 'VEN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 179, 'name' => 'Vietnam, Embajada', 'determinant' => 'VNM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
//            ['id' => 33, 'name' => '', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

        ]);
    }
}
