<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatAdministrativeUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_administrative_units')->insert([
//            ['id' => 1, 'name' => 'Dirección General del Acervo Histórico Diplomático', 'determinant' => 'DGAHD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => 'Consultoría Jurídica', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CJA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 2, 'name' => 'Dirección General de Asuntos Jurídicos', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'ASJ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 3, 'name' => 'Dirección General del Servicio Exterior y de Recursos Humanos', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DSE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 4, 'name' => 'Dirección General de Programación, Organización y Presupuesto', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'POP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 5, 'name' => 'Sindicato Nacional de Trabajadores de la Secretaría de Relaciones Exteriores', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 6, 'name' => 'Dirección General de Bienes Inmuebles y Recursos Materiales', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'IRM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 7, 'name' => 'Dirección General de Protocolo', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'PRO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 8, 'name' => 'Dirección General de Tecnologías de Información e Innovación', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'TIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 9, 'name' => 'Dirección General del Acervo Histórico Diplomático', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'AHD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 10, 'name' => 'Dirección General de Comunicación Social', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DCS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 11, 'name' => 'Jefatura de la Oficina del Canciller', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 12, 'name' => 'Coordinación General de Asesores', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CGA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 13, 'name' => 'Coordinación de Asesores de Oficialía Mayor', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 14, 'name' => 'De aplicación general', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 15, 'name' => 'Unidad de Transparencia', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 16, 'name' => 'Dirección General para Asia-Pacifico', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DAP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 17, 'name' => 'Dirección General para Europa', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DGE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 18, 'name' => 'Dirección General para África y Medio Oriente', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'AMO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 19, 'name' => 'Dirección General para América Latina y el Caribe', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'ALC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 20, 'name' => 'Dirección General para América del Norte', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 21, 'name' => 'Dirección General para Asuntos Espciales', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DAE', 'crated_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 22, 'name' => 'CILA Norte', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 23, 'name' => 'CILA Sur', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 24, 'name' => 'Dirección General de Servicios Consulares', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DSC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 25, 'name' => 'Dirección General de Derechos Humanos y Democracia', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DDH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 26, 'name' => 'Dirección General para la Organización de las Naciones Unidas', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DNU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 27, 'name' => 'Dirección General para Temas Globales', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'TEL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 28, 'name' => 'Dirección General de Organismos y Mecanismos Regionales', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'ORA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 29, 'name' => 'Dirección General de Vinculación con las Organizaciones de la Sociedad Civil', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'VOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 30, 'name' => 'Dirección General de Protección a Mexicanos en el Exterior', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'PME', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 31, 'name' => 'Representaciones de México en el exterior', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 32, 'name' => 'Dirección General de Delegaciones', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DGD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 33, 'name' => 'Delegaciones Locales y Foráneas', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],


            //Unidades Administrativas que faltan....

            ['id' => 34, 'name' => 'Secretaría Particular', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'SPR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 35, 'name' => 'Comisión de personal del servicio exterior mexicano', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DCP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 36, 'name' => 'Centro de enlace diplomático', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CED', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 37, 'name' => 'Dirección general de coordinación política', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DEP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 38, 'name' => 'Instituto Matias Romero', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'IMR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 39, 'name' => 'Subsecretaría de relaciones exteriores', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'SSRE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 40, 'name' => 'Subsecretaría para América del norte', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'SSAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 41, 'name' => 'Instituto de los mexicanos en el exterior', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'IME', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 42, 'name' => 'Sección mexicana de la comisión internacional de límites y aguas entre México y Estados Unidos', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CEU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 43, 'name' => 'Subsecretaría para América latina y el caribe', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'SSAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 44, 'name' => 'Sección mexicana de la comisión internacional de límites y aguas entre México y Guatemala y entre México y Belice', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CGB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 45, 'name' => 'Subsecretaría para asuntos multilaterales y derechos humanos', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'SSMH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 46, 'name' => 'Unidad de administración y finanzas', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'UAF', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 47, 'name' => 'Agencia Mexicana de cooperación internacional para el desarrollo', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'AMI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 48, 'name' => 'Dirección general de cooperación educativa y cultural', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CEC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 49, 'name' => 'Dirección general de cooperación y promoción económica internacional', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'PEI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 50, 'name' => 'Dirección general de cooperación y relaciones económicas bilaterales', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'REB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 51, 'name' => 'Dirección general de cooperación técnica y científica', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'CTC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 52, 'name' => 'Dirección general del proyecyo integración y desarrollo de Mesoamérica', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'IDM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 53, 'name' => 'Dirección general de planeación y cooperación económica internacional', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'PCI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Delegaciones Metropolitanas

            ['id' => 54, 'name' => 'Delegación Álvaro Obregón', 'cat_type_id' => 2, 'specialName' => 'Álvaro Obregón', 'determinant' => 'AOM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 55, 'name' => 'Delegación Benito Juárez', 'cat_type_id' => 2, 'specialName' => 'Benito Juárez', 'determinant' => 'BJM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 56, 'name' => 'Delegación Cuajimalpa de Morelos', 'cat_type_id' => 2, 'specialName' => 'Cuajimalpa de Morelos', 'determinant' => 'CUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 57, 'name' => 'Delegación Cuauhtemoc', 'cat_type_id' => 2, 'specialName' => 'Cuauhtemoc', 'determinant' => 'CUM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 58, 'name' => 'Delegación Gustavo A. Madero', 'cat_type_id' => 2, 'specialName' => 'Gustavo A. Madero', 'determinant' => 'GAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 59, 'name' => 'Delegación Iztacalco', 'cat_type_id' => 2, 'specialName' => 'Iztacalco', 'determinant' => 'IZT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 60, 'name' => 'Delegación Iztapalapa', 'cat_type_id' => 2, 'specialName' => 'Iztapalapa', 'determinant' => 'IZP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 61, 'name' => 'Delegación Miguel Hidalgo', 'cat_type_id' => 2, 'specialName' => 'Miguel Hidalgo', 'determinant' => 'MHM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 62, 'name' => 'Delegación Naucalpan, Estado de México', 'cat_type_id' => 2, 'specialName' => 'Naucalpan, Estado de México', 'determinant' => 'EMN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 63, 'name' => 'Delegación Tlalpan', 'cat_type_id' => 2, 'specialName' => 'Tlalpan', 'determinant' => 'TLM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 64, 'name' => 'Delegación Venustiano Carranza', 'cat_type_id' => 2, 'specialName' => 'Venustiano Carranza', 'determinant' => 'VEM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 65, 'name' => 'Edificio Tlatelolco, Plaza Juárez', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'TCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Delegaciones Foráneas

            ['id' => 66, 'name' => 'Delegación Acapulco, Guerrero', 'cat_type_id' => 3, 'specialName' => 'Acapulco, Guerrero', 'determinant' => 'ACP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 67, 'name' => 'Delegación Aguascalientes, Aguascalientes', 'cat_type_id' => 3, 'specialName' => 'Aguascalientes, Aguascalientes', 'determinant' => 'AGS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 68, 'name' => 'Delegación Campeche, Campeche', 'cat_type_id' => 3, 'specialName' => 'Campeche, Campeche', 'determinant' => 'CAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 69, 'name' => 'Delegación Cancún, Quintana Roo', 'cat_type_id' => 3, 'specialName' => 'Cancún, Quintana Roo', 'determinant' => 'CUN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 70, 'name' => 'Delegación Chihuahua, Chihuahua', 'cat_type_id' => 3, 'specialName' => 'Chihuahua, Chihuahua', 'determinant' => 'CHH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 71, 'name' => 'Delegación Ciudad Juárez, Chihuahua', 'cat_type_id' => 3, 'specialName' => 'Ciudad Juárez, Chihuahua', 'determinant' => 'CJU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 72, 'name' => 'Delegación Ciudad Victoria, Tamaulipas', 'cat_type_id' => 3, 'specialName' => 'Ciudad Victoria, Tamaulipas', 'determinant' => 'CVT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 73, 'name' => 'Delegación Colima, Colima', 'cat_type_id' => 3, 'specialName' => 'Colima, Colima', 'determinant' => 'DCO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 74, 'name' => 'Delegación Cuernavaca, Morelos', 'cat_type_id' => 3, 'specialName' => 'Cuernavaca, Morelos', 'determinant' => 'DMO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 75, 'name' => 'Delegación Culiacán, Sinaloa', 'cat_type_id' => 3, 'specialName' => 'Culiacán, Sinaloa', 'determinant' => 'SIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 76, 'name' => 'Delegación Durango, Durango', 'cat_type_id' => 3, 'specialName' => 'Durango, Durango', 'determinant' => 'DUR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 77, 'name' => 'Delegación Guadalajara, Jalisco', 'cat_type_id' => 3, 'specialName' => 'Guadalajara, Jalisco', 'determinant' => 'JAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 78, 'name' => 'Delegación Hermosillo, Sonora', 'cat_type_id' => 3, 'specialName' => 'Hermosillo, Sonora', 'determinant' => 'SON', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 79, 'name' => 'Delegación Jalapa, Veracruz', 'cat_type_id' => 3, 'specialName' => 'Jalapa, Veracruz', 'determinant' => 'VER', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 80, 'name' => 'Delegación La Paz, Baja California Sur', 'cat_type_id' => 3, 'specialName' => 'La Paz, Baja California Sur', 'determinant' => 'BCS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 81, 'name' => 'Delegación León, Guanajuato', 'cat_type_id' => 3, 'specialName' => 'León, Guanajuato', 'determinant' => 'LEO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 82, 'name' => 'Delegación Mérida, Yucatan', 'cat_type_id' => 3, 'specialName' => 'Mérida, Yucatan', 'determinant' => 'YUC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 83, 'name' => 'Delegación Mexicali, Baja California', 'cat_type_id' => 3, 'specialName' => 'Mexicali, Baja California', 'determinant' => 'BCN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 84, 'name' => 'Delegación Monterrey, Nuevo León', 'cat_type_id' => 3, 'specialName' => 'Monterrey, Nuevo León', 'determinant' => 'NLE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 85, 'name' => 'Delegación Morelia, Michoacán', 'cat_type_id' => 3, 'specialName' => 'Morelia, Michoacán', 'determinant' => 'MOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 86, 'name' => 'Delegación Oaxaca, Oaxaca', 'cat_type_id' => 3, 'specialName' => 'Oaxaca, Oaxaca', 'determinant' => 'OAX', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 87, 'name' => 'Delegación Pachuca, Hidalgo', 'cat_type_id' => 3, 'specialName' => 'Pachuca, Hidalgo', 'determinant' => 'HGO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 88, 'name' => 'Delegación Puebla, Puebla', 'cat_type_id' => 3, 'specialName' => 'Puebla, Puebla', 'determinant' => 'PUE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 89, 'name' => 'Delegación Querétaro, Querétaro', 'cat_type_id' => 3, 'specialName' => 'Querétaro, Querétaro', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 90, 'name' => 'Delegación San Luis Potosi, San Luis Potosi', 'cat_type_id' => 3, 'specialName' => 'San Luis Potosi, San Luis Potosi', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 91, 'name' => 'Delegación Tepic, Nayarit', 'cat_type_id' => 3, 'specialName' => 'Tepic, Nayarit', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 92, 'name' => 'Delegación Tijuana, Baja California Norte', 'cat_type_id' => 3, 'specialName' => 'Tijuana, Baja California Norte', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 93, 'name' => 'Delegación Tlaxcala, Tlaxcala', 'cat_type_id' => 3, 'specialName' => 'Tlaxcala, Tlaxcala', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 94, 'name' => 'Delegación Toluca, Estado de México', 'cat_type_id' => 3, 'specialName' => 'Toluca, Estado de México', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 95, 'name' => 'Delegación Torreón, Coahuila', 'cat_type_id' => 3, 'specialName' => 'Torreón, Coahuila', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 96, 'name' => 'Delegación Tuxtla Gutierrez, Chiapas', 'cat_type_id' => 3, 'specialName' => 'Tuxtla Gutierrez, Chiapas', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 97, 'name' => 'Delegación Villahermosa, Tabasco', 'cat_type_id' => 3, 'specialName' => 'Villahermosa, Tabasco', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 98, 'name' => 'Delegación Zacatecas, Zacatecas', 'cat_type_id' => 3, 'specialName' => 'Zacatecas, Zacatecas', 'determinant' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Embajadas

            ['id' => 99, 'name' => 'Alemania, Embajada', 'cat_type_id' => 4, 'specialName' => 'Alemania', 'determinant' => 'ALE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 100, 'name' => 'Arabia Saudita, Embajada', 'cat_type_id' => 4, 'specialName' => 'Arabia Saudita', 'determinant' => 'ASA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 101, 'name' => 'Argelia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Argelia', 'determinant' => 'ARL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 102, 'name' => 'Argentina, Embajada', 'cat_type_id' => 4, 'specialName' => 'Argentina', 'determinant' => 'ARG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 103, 'name' => 'Australia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Australia', 'determinant' => 'AUS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 104, 'name' => 'Austria, Embajada', 'cat_type_id' => 4, 'specialName' => 'Austria', 'determinant' => 'AUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 105, 'name' => 'Azerbaiyan, Embajada', 'cat_type_id' => 4, 'specialName' => 'Azerbaiyan', 'determinant' => 'AZE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 106, 'name' => 'Bélgica, Embajada', 'cat_type_id' => 4, 'specialName' => 'Bélgica', 'determinant' => 'BEL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 107, 'name' => 'Belize, Embajada', 'cat_type_id' => 4, 'specialName' => 'Belize', 'determinant' => 'BEE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 108, 'name' => 'Bolivia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Bolivia', 'determinant' => 'BOL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 109, 'name' => 'Brasil, Embajada', 'cat_type_id' => 4, 'specialName' => 'Brasil', 'determinant' => 'BRA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 110, 'name' => 'Canadá, Embajada', 'cat_type_id' => 4, 'specialName' => 'Canadá', 'determinant' => 'CAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 111, 'name' => 'Chile, Embajada', 'cat_type_id' => 4, 'specialName' => 'Chile', 'determinant' => 'CHI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 112, 'name' => 'China, Embajada', 'cat_type_id' => 4, 'specialName' => 'China', 'determinant' => 'CHN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 113, 'name' => 'Colombia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Colombia', 'determinant' => 'COL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 114, 'name' => 'Corea, Embajada', 'cat_type_id' => 4, 'specialName' => 'Corea', 'determinant' => 'COR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 115, 'name' => 'Costa Rica, Embajada', 'cat_type_id' => 4, 'specialName' => 'Costa Rica', 'determinant' => 'CRI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 116, 'name' => 'Cuba, Embajada', 'cat_type_id' => 4, 'specialName' => 'Cuba', 'determinant' => 'CUB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 117, 'name' => 'Dinamarca, Embajada', 'cat_type_id' => 4, 'specialName' => 'Dinamarca', 'determinant' => 'DIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 118, 'name' => 'Ecuador, Embajada', 'cat_type_id' => 4, 'specialName' => 'Ecuador', 'determinant' => 'ECU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 119, 'name' => 'Egipto, Embajada', 'cat_type_id' => 4, 'specialName' => 'Egipto', 'determinant' => 'RAE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 120, 'name' => 'El Salvador, Embajada', 'cat_type_id' => 4, 'specialName' => 'El Salvador', 'determinant' => 'ESA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 121, 'name' => 'Emiratos Árabe Unidos, Embajada', 'cat_type_id' => 4, 'specialName' => 'Emiratos Árabe Unidos', 'determinant' => 'EAU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 122, 'name' => 'España, Embajada', 'cat_type_id' => 4, 'specialName' => 'España', 'determinant' => 'ESP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 123, 'name' => 'Estados Unidos, Embajada', 'cat_type_id' => 4, 'specialName' => 'Estados Unidos', 'determinant' => 'EUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 124, 'name' => 'Etiopia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Etiopia', 'determinant' => 'ETI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 125, 'name' => 'Federación de Rusia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Federación de Rusia', 'determinant' => 'RUS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 126, 'name' => 'Filipinas, Embajada', 'cat_type_id' => 4, 'specialName' => 'Filipinas', 'determinant' => 'FIL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 127, 'name' => 'Finlandia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Finlandia', 'determinant' => 'FIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 128, 'name' => 'Francia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Francia', 'determinant' => 'FRA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 129, 'name' => 'Ghana, Embajada', 'cat_type_id' => 4, 'specialName' => 'Ghana', 'determinant' => 'GHA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 130, 'name' => 'Grecia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Grecia', 'determinant' => 'GRE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 131, 'name' => 'Guatemala, Embajada', 'cat_type_id' => 4, 'specialName' => 'Guatemala', 'determinant' => 'GUA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 132, 'name' => 'Guyana, Embajada', 'cat_type_id' => 4, 'specialName' => 'Guyana', 'determinant' => 'GUY', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 133, 'name' => 'Haití, Embajada', 'cat_type_id' => 4, 'specialName' => 'Haití', 'determinant' => 'HAI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 134, 'name' => 'Honduras, Embajada', 'cat_type_id' => 4, 'specialName' => 'Honduras', 'determinant' => 'HON', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 135, 'name' => 'Hungría, Embajada', 'cat_type_id' => 4, 'specialName' => 'Hungría', 'determinant' => 'HUN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 136, 'name' => 'India, Embajada', 'cat_type_id' => 4, 'specialName' => 'India', 'determinant' => 'IND', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 137, 'name' => 'Indonesia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Indonesia', 'determinant' => 'INO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 138, 'name' => 'Irán, Embajada', 'cat_type_id' => 4, 'specialName' => 'Irán', 'determinant' => 'IRN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 139, 'name' => 'Irlanda, Embajada', 'cat_type_id' => 4, 'specialName' => 'Irlanda', 'determinant' => 'IRL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 140, 'name' => 'Israel, Embajada', 'cat_type_id' => 4, 'specialName' => 'Israel', 'determinant' => 'ISR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 141, 'name' => 'Italia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Italia', 'determinant' => 'ITA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 142, 'name' => 'Jamaica, Embajada', 'cat_type_id' => 4, 'specialName' => 'Jamaica', 'determinant' => 'JAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 143, 'name' => 'Japón, Embajada', 'cat_type_id' => 4, 'specialName' => 'Japón', 'determinant' => 'JAP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 144, 'name' => 'Jordania, Embajada', 'cat_type_id' => 4, 'specialName' => 'Jordania', 'determinant' => 'JOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 145, 'name' => 'Kenia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Kenia', 'determinant' => 'KEN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 146, 'name' => 'Kuwait, Embajada', 'cat_type_id' => 4, 'specialName' => 'Kuwait', 'determinant' => 'KWT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 147, 'name' => 'Líbano, Embajada', 'cat_type_id' => 4, 'specialName' => 'Líbano', 'determinant' => 'LIB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 148, 'name' => 'Malasia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Malasia', 'determinant' => 'MLS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 149, 'name' => 'Marruecos, Embajada', 'cat_type_id' => 4, 'specialName' => 'Marruecos', 'determinant' => 'MAR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 150, 'name' => 'Nicaragua, Embajada', 'cat_type_id' => 4, 'specialName' => 'Nicaragua', 'determinant' => 'NIC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 151, 'name' => 'Nigeria, Embajada', 'cat_type_id' => 4, 'specialName' => 'Nigeria', 'determinant' => 'NIG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 152, 'name' => 'Noruega, Embajada', 'cat_type_id' => 4, 'specialName' => 'Noruega', 'determinant' => 'NOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 153, 'name' => 'Nueva Zelanda, Embajada', 'cat_type_id' => 4, 'specialName' => 'Nueva Zelanda', 'determinant' => 'NZE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 154, 'name' => 'Países Bajos, Embajada', 'cat_type_id' => 4, 'specialName' => 'Países Bajos', 'determinant' => 'PBA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 155, 'name' => 'Panamá, Embajada', 'cat_type_id' => 4, 'specialName' => 'Panamá', 'determinant' => 'PAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 156, 'name' => 'Paraguay, Embajada', 'cat_type_id' => 4, 'specialName' => 'Paraguay', 'determinant' => 'PAY', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 157, 'name' => 'Perú, Embajada', 'cat_type_id' => 4, 'specialName' => 'Perú', 'determinant' => 'PER', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 158, 'name' => 'Polonia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Polonia', 'determinant' => 'POL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 159, 'name' => 'Portugal, Embajada', 'cat_type_id' => 4, 'specialName' => 'Portugal', 'determinant' => 'POR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 160, 'name' => 'Qatar, Embajada', 'cat_type_id' => 4, 'specialName' => 'Qatar', 'determinant' => 'QAT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 161, 'name' => 'Reino Unido de la Gran Bretaña e Irlanda del Norte, Embajada', 'cat_type_id' => 4, 'specialName' => 'Reino Unido de la Gran Bretaña e Irlanda del Norte', 'determinant' => 'GBR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 162, 'name' => 'República Checa, Embajada', 'cat_type_id' => 4, 'specialName' => 'República Checa', 'determinant' => 'CHE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 163, 'name' => 'República Dominicana, Embajada', 'cat_type_id' => 4, 'specialName' => 'República Dominicana', 'determinant' => 'DOM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 164, 'name' => 'Rumania, Embajada', 'cat_type_id' => 4, 'specialName' => 'Rumania', 'determinant' => 'RUM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 165, 'name' => 'Santa Lucia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Santa Lucia', 'determinant' => 'LCA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 166, 'name' => 'Santa Sede, El Vaticano, Embajada', 'cat_type_id' => 4, 'specialName' => 'Santa Sede, El Vaticano', 'determinant' => 'VAT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 167, 'name' => 'Serbia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Serbia', 'determinant' => 'SEB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 168, 'name' => 'Singapur, Embajada', 'cat_type_id' => 4, 'specialName' => 'Singapur', 'determinant' => 'SIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 169, 'name' => 'Sudáfrica, Embajada', 'cat_type_id' => 4, 'specialName' => 'Sudáfrica', 'determinant' => 'SUD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 170, 'name' => 'Suecia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Suecia', 'determinant' => 'SUE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 171, 'name' => 'Suiza, Embajada', 'cat_type_id' => 4, 'specialName' => 'Suiza', 'determinant' => 'SUI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 172, 'name' => 'Tailandia, Embajada', 'cat_type_id' => 4, 'specialName' => 'Tailandia', 'determinant' => 'TAI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 173, 'name' => 'Trinidad y Tobago, Embajada', 'cat_type_id' => 4, 'specialName' => 'Trinidad y Tobago', 'determinant' => 'TRT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 174, 'name' => 'Turquía, Embajada', 'cat_type_id' => 4, 'specialName' => 'Turquía', 'determinant' => 'TUR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 175, 'name' => 'Ucrania, Embajada', 'cat_type_id' => 4, 'specialName' => 'Ucrania', 'determinant' => 'UCR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 176, 'name' => 'Uruguay, Embajada', 'cat_type_id' => 4, 'specialName' => 'Uruguay', 'determinant' => 'URU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 177, 'name' => 'Venezuela, Embajada', 'cat_type_id' => 4, 'specialName' => 'Venezuela', 'determinant' => 'VEN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 178, 'name' => 'Vietnam, Embajada', 'cat_type_id' => 4, 'specialName' => 'Vietnam', 'determinant' => 'VNM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Administrador
//            ['id' => 179, 'name' => 'Dirección General del Acervo Histórico Diplomático', 'cat_type_id' => 1, 'specialName' => null, 'determinant' => 'DGAHD', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            //Consulados

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ALB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ALM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ACH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ATL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'AMM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ATN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ATM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'BAR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'BOI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'BOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'BOM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'BRO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'BRM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CLG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CHO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CHM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'CHL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DEL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DRM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DEN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DNM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DET', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DEM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DOU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'DGM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'EAG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'EAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'EPA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'EPM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ETB', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'FIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'FIM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'FRK', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'FRE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'FRM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'GUN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'HKO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'HOU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'HOM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'HOS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'INI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'INM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'KAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'KAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LAR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LRM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LVN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LVM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LEA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LIR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LON', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'LAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MCM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MIM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MIL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MKE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'MON', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NOG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NGM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NUO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NUY', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NYM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NYL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'NYS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'OMH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'OMM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ORL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'ORM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'OXN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'OXM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'PHO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'PHM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'POT', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'POM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'PSI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'PSM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'QUE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'RLG', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'RLM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'RIO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SAC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SCM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SAI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SLM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SBE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SBM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SBS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SDI', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SDM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SFR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SFM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SJO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SJM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SJU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SPA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'STA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'STM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SAO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SEA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SEM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'SHA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'TEU', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'TOR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'TUC', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'TUM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'VAN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'WAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'WAM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'WIN', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'YUM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 1, 'name' => '', 'cat_type_id' => 5, 'specialName' => null, 'determinant' => 'YMM', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
        

        ]);
    }
}
