<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatDescriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_descriptions')->insert([
            ['id' => 1, 'cat_series_id' => 1, 'description' => 'Información sobre la opinión Institucional de las Iniciativas de ley presentadas por los legisladores ante el Congreso de la Unión, vinculadas a las funciones de la Secretaría de Relaciones Exteriores o a los asuntos que ésta despacha.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 2, 'cat_series_id' => 1, 'description' => 'Formulación de proyectos de iniciativas de leyes o decretos, así como de reglamentos, acuerdos, circulares y demás disposiciones relacionadas con la competencia de la Secretaría o pronunciándose sobre las que propongan las demás unidades administrativas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 3, 'cat_series_id' => 2, 'description' => 'Gestión u opinión sobre los convenios, acuerdos y bases de coordinación y concertación, que en el ámbito nacional suscriban los servidores públicos competentes de la Secretaría, cuando así lo soliciten.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 4, 'cat_series_id' => 3, 'description' => 'Opinión sobre las disposiciones que deban ser publicadas en el Diario Oficial de la Federación y, en su caso, tramitar su publicación.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 5, 'cat_series_id' => 4, 'description' => 'Certificación de firmas de los documentos expedidos por los miembros del Servicio Exterior Mexicano, adscritos en el extranjero, en el ejercicio de sus funciones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 6, 'cat_series_id' => 5, 'description' => 'Intervención en los procedimientos de extradición y tramitar las solicitudes de detención provisional y formal correspondientes a lo que establece la Ley de Extradición Internacional.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 7, 'cat_series_id' => 6, 'description' => 'Información relativa a las asesorías en materia de derecho internacional (privilegios e inmunidades) y derecho extranjero (empleados locales) a las unidades administrativas, representaciones en el exterior y a los abogados extranjeros respecto de los casos e instrumentos jurídicos que ameriten el diseño de estrategias, a fin de proteger los intereses del Estado Mexicano.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 8, 'cat_series_id' => 6, 'description' => 'Trámite de las solicitudes de asistencia jurídica que requieran las autoridades de la República Mexicana o extranjeras.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 9, 'cat_series_id' => 7, 'description' => 'Gestión y seguimiento de las diligencias para resolver una demanda contra la SRE, por la existencia de una controversia o conflicto de interés, es decir, la sustentación de derechos e intereses contradictorios o contrapuestos a la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 10, 'cat_series_id' => 8, 'description' => 'Documentación derivada de las diligencias para representar legalmente a la Secretaría en toda clase de juicios en que sea parte: agrarios, civiles, mercantiles, de nulidad, etc.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 11, 'cat_series_id' => 9, 'description' => 'Protección de los derechos humanos y derechos fundamentales establecidos en la Constitución, así como en los Tratados Internacionales de los que México sea parte, cuando estos son violados por normas generales, actos u omisiones de autoridad o de particulares señalados en la ley; representando al Presidente de la República, al Secretario, a los Subsecretarios, al Oficial Mayor y demás servidores públicos de esta dependencia en todos los trámites de juicios de amparo establecidos por la Ley de Amparo, Reglamentaria de los artículos 103 y 107 de la Constitución, relacionados con las funciones y competencias de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 12, 'cat_series_id' => 10, 'description' => 'Información para la elaboración del Documento de Planeación de las Inversiones del Ramo 05 Relaciones Exteriores; relacionada con el registro en Cartera de sus Programas y Proyectos de Inversión; así como la información relativa a las solicitudes de autorización de los Oficios de Liberación de Inversión de la Dirección General de Bienes Inmuebles y Recursos Materias, y/o Dirección General de Tecnologías de la Información e Innovación, y/o Dirección General de Delegaciones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 13, 'cat_series_id' => 11, 'description' => 'Análisis, revisión técnica y seguimiento de autorización de los proyectos de manuales de organización específicos emitidos por las Unidades Responsables para efectos de su elaboración o actualización.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 14, 'cat_series_id' => 12, 'description' => 'Establecimiento de las actividades inherentes a los procesos específicos de las Unidades Responsables, atribuidas en el Reglamento Interior de la Secretaría de Relaciones Exteriores y en el Manual de Organización General.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 15, 'cat_series_id' => 13, 'description' => 'Documentos que se generan con motivo de los programas y proyectos que se emprenden para la modernización de los procesos de la dependencia, los cuales agregan valora la gestión institucional y apoyan el cumplimiento de metas y con la finalidad de dar cumplimiento al programa de mediano plazo que promueva la eficiencia y eficacia en la gestión pública a través de compromisos e indicadores formalizados por los titulares de las dependencias y entidades de la administración pública federal.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 16, 'cat_series_id' => 14, 'description' => 'Integración del presupuesto a nivel Secretaría de Relaciones Exteriores, el cual se envía a la Secretaría de Hacienda y Crédito Público, para su revisión, y autorización de la Cámara de Diputados, una vez autorizado la Dirección de Programación y Presupuesto lo hace del conocimiento a las Unidades responsables.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 17, 'cat_series_id' => 15, 'description' => 'Modificar el presupuesto asignado de las Unidades Responsables para satisfacer sus necesidades de operación, con el fin de cumplir con sus objetivos y metas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 18, 'cat_series_id' => 16, 'description' => 'Proceso de calidad regulatoria para las normas, acuerdos y otros instrumentos normativos de la Secretaría de Relaciones Exteriores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 19, 'cat_series_id' => 17, 'description' => 'Desarrollo de proyectos específicos que permitan mecanismos de evaluación institucional, de rendimiento, programas de capacitación, clima organizacional, entre otros.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 20, 'cat_series_id' => 18, 'description' => 'Integración, actualización, control y resguardo de la documentación generada durante la trayectoria laboral de los servidores públicos de la Secretaría de Relaciones Exteriores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 21, 'cat_series_id' => 19, 'description' => 'Actualización y registro de las estructuras de la Cancillería y sus Órganos Administrativos Desconcentrados, ante la Secretaría de la Función Pública, así como de creación, conversión y cancelación de plazas ante la Secretaría de Hacienda y Crédito Público.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 22, 'cat_series_id' => 20, 'description' => 'Procesamiento de las nóminas para el pago del personal adscrito en territorio nacional, en el extranjero y los prestadores de servicios profesionales, así como el entero de las contribuciones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 23, 'cat_series_id' => 21, 'description' => 'Elección del personal más idóneo para un puesto de trabajo considerando las necesidades de la Secretaría de Relaciones Exteriores y el perfil de puesto, para la ocupación de las plazas vacantes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 24, 'cat_series_id' => 22, 'description' => 'Control y registro de asistencia aplicables a los servidores públicos de la Secretaría de Relaciones Exteriores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 25, 'cat_series_id' => 23, 'description' => 'Valoración cuantitativa y cualitativa del rendimiento de los servidores públicos en supuesto, operando a través de indicadores previamente establecidos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 26, 'cat_series_id' => 24, 'description' => 'Trámites de prestaciones y afiliatorios que la Secretaría realiza ante el ISSSTE a favor del servidor público.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 27, 'cat_series_id' => 25, 'description' => 'Aportaciones correspondientes al Fondo de Ahorro Capitalizable de los Trabajadores al Servicio del Estado (FONAC) del personal operativo de base y confianza inscrito para la gestión de pago del personal desincorporado y proceso de liquidación anual.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 28, 'cat_series_id' => 26, 'description' => 'Atención y seguimiento a los requerimientos planteados a la Secretaría por la Organización Sindical, así como difundir la normatividad y procedimientos que regulan las relaciones laborales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 29, 'cat_series_id' => 26, 'description' => 'Información de las acciones encaminadas a asegurar condiciones dignas de seguridad e higiene laboral y generar mediante la unidad la suficiente capacidad de negociación como para establecer una dinámica de dialogo social entre el empleado y los trabajadores con el objetivo de buscar el bienestar de los miembros.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 30, 'cat_series_id' => 27, 'description' => 'Comisiones de Seguridad, Higiene y Medio Ambiente en el Trabajo, que tienen como objetivo la detección y evaluación de riesgos que representen la posibilidad de un daño a la salud ya la integridad física y mental de las y los trabajadores con la finalidad de aplicar las medidas necesarias para su control, conforme a la normatividad aplicable en la materia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 31, 'cat_series_id' => 28, 'description' => 'Integración, actualización, control y resguardo de la documentación generada por la operación del Programa Anual de Capacitación.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 32, 'cat_series_id' => 29, 'description' => 'Coordinación y promoción de los programas de servicio social y prácticas profesionales de estudiantes de los niveles medio superior y superior en la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 33, 'cat_series_id' => 30, 'description' => 'Integración, actualización, control y resguardo de la documentación generada por la operación del Comité de Ética y de Prevención de Conflictos de Interés (CEPCI), con relación a las denuncias recibidas en el seno del mismo.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 34, 'cat_series_id' => 31, 'description' => 'Documentación recibida y generada que comprueba las gestiones de envío de recursos para los gastos de operación de las representaciones de México en el Exterior, tanto ordinarias como extraordinarias.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 35, 'cat_series_id' => 31, 'description' => 'Documentación correspondiente al trámite y adquisición de viáticos y pasajes requeridos por el personal de Cancillería en el desempeño de las comisiones oficiales encomendadas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 36, 'cat_series_id' => 31, 'description' => 'Gestión administrativa correspondiente al trámite y adquisición de viáticos y pasajes requeridos por los miembros del Servicio Exterior Mexicano en el desempeño de las comisiones oficiales encomendadas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 37, 'cat_series_id' => 31, 'description' => 'Acciones encaminada para realizar las asignaciones destinadas a cubrir los gastos que ocasione la instalación de los miembros del Servicio Exterior Mexicano, cuando por el desempeño de funciones oficiales se vea precisado a permanecer fuera de su residencia en forma transitoria o permanente, incluyendo en su caso el traslado de menaje de casa; y pasajes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 38, 'cat_series_id' => 32, 'description' => 'Control, conciliación y reporte a la Tesorería de la Federación del Entero de la Recaudación consular mensual, que realizan las Representaciones de México en el exterior, así como la recepción de su documentación comprobatoria y justificativa.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 39, 'cat_series_id' => 33, 'description' => 'Información que refleja el detalle de las operaciones diarias, cuenta de mayor, balanzas mensuales e inventarios.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 40, 'cat_series_id' => 34, 'description' => 'Información que refleja el detalle de las operaciones diarias, cuenta de mayor, balanzas mensuales e inventarios.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 41, 'cat_series_id' => 34, 'description' => 'Documento presupuestario mediante el cual las dependencias realizan el pago y registro de las operaciones presupuestarias con cargo al Presupuesto de Egresos de la Federación para la adquisición de bienes muebles, inmuebles e intangibles así como para el pago de inversión pública.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 42, 'cat_series_id' => 35, 'description' => 'Comprobación de las erogaciones realizadas por las Representaciones de México en el Exterior, así como la documentación soporte de los ingresos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 43, 'cat_series_id' => 36, 'description' => 'Conducir las acciones relativas al pago del gasto corriente a favor de un beneficiario y en el cual se adjunta la documentación comprobatoria y justificativa del gasto.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 44, 'cat_series_id' => 37, 'description' => 'Integración y movimiento del presupuesto correspondiente a las Representaciones de México en el Exterior, el cual es validado y autorizado por las Unidades Normativas de Gasto, para su revisión, y autorización.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 45, 'cat_series_id' => 38, 'description' => 'Mecanismo presupuestario que la Secretaría de Hacienda y Crédito Público autoriza para que la Secretaría de Relaciones Exteriores cubra compromisos que solo pueden ser liquidados mediante la expedición de cheques.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 46, 'cat_series_id' => 39, 'description' => 'Conciliación de recuperación de inversiones públicas que realizan el centro de registro Servicio de Administración Tributaria (SAT) y el Ramo 05 Secretaría de Relaciones Exteriores (SRE) y Conciliación de Cuentas Conectoras del Sistema Integral de Contabilidad Gubernamental y las Correlativas del Sistema de Contabilidad del Poder Ejecutivo que se realizan entre la Tesorería de la Federación y la SRE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 47, 'cat_series_id' => 40, 'description' => 'Mecanismo presupuestario que la Secretaría de Hacienda y Crédito Público autoriza para que la Secretaría de Relaciones Exteriores cubra compromisos derivados del ejercicio de sus funciones, programas y presupuestos autorizados, con sus debidas excepciones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 48, 'cat_series_id' => 41, 'description' => 'Coordinar, integrar y operar todas aquellas acciones que coadyuven a fomentar el manejo ambiental de los recursos en las Unidades Administrativas de la Secretaría de Relaciones Exteriores, vigilando la aplicación de las disposiciones en la materia, emitidas por la SEMARNAT (Secretaría de Medio Ambiente y Recursos Naturales) y CONUEE (Comisión Nacional para el Uso Eficiente de la Energía); instrumentando programas de uso eficiente del agua, energía eléctrica, combustibles, materiales de oficina y consumo responsable para el ahorro de los recursos, sin afectar la funcionalidad en los inmuebles.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 49, 'cat_series_id' => 42, 'description' => 'Contratación, adquisición y/o arrendamiento de bienes y/o servicios; realizados a través del Procedimiento de Licitación Pública.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 52, 'cat_series_id' => 44, 'description' => 'Control y seguimiento de los contratos, pedidos y convenios modificatorios celebrados de las adquisiciones, arrendamientos o servicios contratados por la Secretaría de Relaciones Exteriores en territorio nacional.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 53, 'cat_series_id' => null, 'description' => 'Reglamentación que fija las políticas y criterios generales para una mejor administración de los actos que se deriven de la contratación de empleados locales y/o prestadores de servicios profesionales, que sin formar parte del Servicio Exterior Mexicano (SEM), ni ocupar plaza de estructura federal, es contratado localmente por una Embajada, Misión, Delegación Permanente u Oficina Consular de México en el extranjero para prestar determinados servicios administrativos o de otra índole, en apoyo a las labores del personal del SEM.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 54, 'cat_series_id' => 44, 'description' => 'Gestión del aseguramiento de los bienes muebles, propiedad de la Secretaría y dar seguimiento a los procesos de reclamación e indemnización de los daños ocasionados por siniestros al patrimonio de esta dependencia ante la compañía Aseguradora, así como mantener un adecuado control y seguimiento sobre las fianzas y garantías constituidas para el cumplimiento de los contratos celebrados en la Dependencia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 55, 'cat_series_id' => 45, 'description' => 'Control y seguimiento documental de los servicios de mantenimiento preventivo y correctivo de los bienes muebles e inmuebles de propiedad, a cargo y/o bajo responsabilidad de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 56, 'cat_series_id' => 46, 'description' => 'Control y seguimiento del sistema de registro de proveedores y contratistas, el cual tiene como finalidad que una licitante al adquirir el carácter de contratista podrá solicitar su inscripción al Registro Único de Proveedores y de Contratistas (RUPC).', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 57, 'cat_series_id' => 47, 'description' => 'Control y registro de los bienes inmuebles que ocupa la Secretaría y sus órganos des concentrados en el territorio nacional.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 58, 'cat_series_id' => 48, 'description' => 'Validación y verificación física de los bienes muebles instrumentales; así como el registro, afectación, disposición final y baja de los mismos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 59, 'cat_series_id' => 48, 'description' => 'Administración y control del patrimonio artístico que se encuentra bajo resguardo de la Secretaría de Relaciones Exteriores; y que están asignados a las unidades administrativas tanto en territorio nacional como en las Representaciones de México en el exterior; así como el registro, asignación y baja de los mismos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 60, 'cat_series_id' => 49, 'description' => 'Administración y control detallado, ordenado y de forma valorada de los inmuebles que componen el patrimonio inmobiliario propiedad de la Secretaría de Relaciones Exteriores, con la finalidad de llevar el registro de la existencia, valor de los mismos, sus características y condiciones de uso a través del inventario físico para garantizar un mejor control del uso y aprovechamiento de los inmuebles.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 61, 'cat_series_id' => 50, 'description' => 'Recepción de bienes de consumo, almacenamiento, registro de entradas y salidas en el Sistema de Control de Almacén y distribución a las unidades administrativas de la Cancillería.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 62, 'cat_series_id' => 51, 'description' => 'Contratación de obras públicas y servicios relacionados con las mismas, a través de los procedimientos de Licitación Pública, Invitación a Cuando Menos Tres Personas y Adjudicación Directa.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 63, 'cat_series_id' => 52, 'description' => 'Seguimiento del Programa Anual de adquisiciones, arrendamientos y servicios, así como dictaminar y, en su caso, exceptuar del procedimiento de licitación pública a través de adjudicación directa las contrataciones que por su naturaleza así lo requieran.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 64, 'cat_series_id' => 53, 'description' => 'Gestiones para garantizar la eficacia, transparencia a la gestión y desempeño de la administración, así como coadyuvar al logro efectivo y óptimo aprovechamiento de los bienes muebles, constituyendo un instrumento que permite tomar decisiones para la afectación, disposición final y baja de los bienes muebles.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 65, 'cat_series_id' => 54, 'description' => 'Seguimiento de contratos emanados de fallos de Licitaciones, Invitación a Cuando Menos tres personas, o por Adjudicaciones directas, para la contratación, ejecución y cierre de obra pública, así como las estimaciones y número generadores que se derivan de los mismos, hasta la conclusión de los trabajos de obra o remodelación.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 66, 'cat_series_id' => 55, 'description' => 'Controlar el pago oportuno de los servicios básicos de suministro de energía eléctrica, impuesto predial yagua potable y residual, en inmuebles que ocupa la Secretaría en la Ciudad de México, así como trámites correspondientes a altas y bajas de las cuentas y contratos por dichos servicios.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 67, 'cat_series_id' => 56, 'description' => 'Administración y control de los servicios de envío y recepción de documentos oficiales a través de la Valija Diplomática, Intercambio Gubernamental y Mensajería Nacional.    ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 68, 'cat_series_id' => 57, 'description' => 'Optimizar y racionalizar el uso, conservación, guarda y funcionamiento de todo el mobiliario y equipo, a efecto de garantizar el buen estado y aspecto físico, sin permitir su deterioro, para procurar un desarrollo eficaz y eficiente de las actividades de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 69, 'cat_series_id' => 58, 'description' => 'Documentar y sustentar lo relacionado al ingreso, baja, resguardo, uso y mantenimiento del parque vehicular terrestre de acuerdo a los requerimientos de las unidades administrativas de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 70, 'cat_series_id' => 59, 'description' => 'Administración y control del suministro de combustible (Gasolina y Diésel) mediante monedero electrónico (tarjetas plásticas electrónicas).', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 71, 'cat_series_id' => 60, 'description' => 'Información relativa a la coordinación de agenda para llevar a cabo diversas Reuniones de Trabajo, Conferencias y Eventos en las Salas de Conferencias y Eventos Sociales de la Cancillería. ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 72, 'cat_series_id' => 61, 'description' => 'Diseño e implementación de estrategias de prevención y gestión integral del riesgo a través de verificaciones, asesorías internas y enlace con autoridades de protección civil, direccionamiento y administración de los recursos humanos y materiales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 73, 'cat_series_id' => 62, 'description' => 'Gestión de servicios de infraestructura, Seguridad y telecomunicaciones en las Unidades Administrativas, así como en las Representaciones de México en el Exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 74, 'cat_series_id' => 63, 'description' => 'Apoyo con herramienta tecnológica (Joomla) que permite publicar información para la operación del portal web de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 75, 'cat_series_id' => 64, 'description' => 'Administración del servicio de equipamiento de equipo de cómputo, apoyar y dar soporte a los usuarios de la Cancillería México en el manejo, funcionamiento y uso apropiado de las herramientas de hardware y software, así como en los servicios de correo electrónico e internet.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 76, 'cat_series_id' => 65, 'description' => 'Gestiones para establecer y vigilar los mecanismos que permitan la administración de la seguridad de la información, implementar y operar los controles de seguridad de la información y establecer y actualizar un repositorio de configuraciones, en el que se integren las soluciones tecnológicas y sus componentes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 77, 'cat_series_id' => 66, 'description' => 'Establecer y vigilar los mecanismos que permitan la administración de la seguridad de la información, implementar y operar los controles de seguridad de la información y establecer y actualizar un repositorio de configuraciones, en el que se integren las soluciones tecnológicas y sus componentes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 78, 'cat_series_id' => 67, 'description' => 'Dirección y coordinación de la gestión documental de la Secretaría con base en la normatividad vigente y aplicable en materia de organización, conservación, uso, acceso y valoración de los archivos producidos por las Unidades Administrativas y por las Representaciones de México en el exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 79, 'cat_series_id' => 68, 'description' => 'Dirección, coordinación y supervisión de los servicios de información bibliográfica del Acervo Histórico Diplomático. Apoyar la organización de las bibliotecas de las representaciones diplomáticas y consulares en el exterior y mantener actualizado sus acervos con las publicaciones de la Secretaría de Relaciones Exteriores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 80, 'cat_series_id' => 69, 'description' => 'Difusión de los acervos fotográficos de la dirección general en instituciones educativas y centros de investigación nacionales y extranjeros. Supervisión de que se lleven a cabo los inventarios de material iconográfico.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 81, 'cat_series_id' => 70, 'description' => 'Coordinación de proyectos de investigación sobre política exterior de México, basado en los acervos documentales; establecimiento de vínculos con otras instituciones académicas para realizar conjuntamente proyectos de investigación; elaboración del Programa Editorial del Acervo Histórico Diplomático, en particular, y de la Secretaría en general; convocatoria al Premio Genaro Estrada.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 82, 'cat_series_id' => 71, 'description' => 'Apoyo con una herramienta o metodología tecnológica que permite publicar en internet o intranet la información de las áreas sustantivas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 83, 'cat_series_id' => 72, 'description' => 'Información derivada de las estrategias de comunicación encaminadas a la difusión de las campañas de publicidad de la Secretaría de Relaciones Exteriores (SRE), con el fin de dar a conocer la política exterior mexicana y las tareas sustantivas de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 84, 'cat_series_id' => 73, 'description' => 'Información derivada de las acciones para difundir de manera adecuada y oportuna las actividades de los diversos funcionarios de la cancillería, embajadores y cónsules, tanto en México como en el exterior, para que sus declaraciones y eventos proyecten de manera puntual el acontecer de la política exterior, además de autorizar los diferentes insumos (síntesis, monitoreo y comunicados de prensa) que permitan una adecuada toma de decisiones, así como sugerir la pauta publicitaria. Así como de las acciones para el estudio, diseño, elaboración y programación de material multimedia para cubrir con fotografía y video las actividades de los principales funcionarios de la Cancillería, produciendo material gráfico en foto y video para los medios de comunicación, consumo interno, archivo institucional y apoyo a redes sociales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 85, 'cat_series_id' => 74, 'description' => 'Información relativa a las acciones para difundir la política exterior mexicana, así como los objetivos, programas y acciones de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 86, 'cat_series_id' => 75, 'description' => 'Difusión oportuna de las actividades de los diversos funcionarios de la Cancillería, embajadores y cónsules, tanto en México como en el exterior. Elaborar, registrar y publicar periódicamente boletines informativos sobre el quehacer continuo institucional en los medios de comunicación.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 87, 'cat_series_id' => 76, 'description' => 'Selección de noticias publicadas en medios internacionales tanto sobre México como del ámbito internacional, a fin mantener informados a los funcionarios de la dependencia y facilitar su toma de decisiones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 88, 'cat_series_id' => 77, 'description' => 'Integración de informes y evidencias de la gestión y del estado que guarda la Secretaría en el desarrollo de sus funciones para dar cuenta al Congreso de la Unión y comparecer ante cualquiera de las Cámaras cuando para ello sea requerido.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 89, 'cat_series_id' => 78, 'description' => 'Establecimiento, supervisión, evaluación, actualización y mejora continua del Sistema de Control Interno Institucional, análisis y evaluación de riesgos, y seguimiento del desempeño institucional, para el cumplimiento del objetivo del control interno en las categorías correspondientes (operación, información, cumplimiento y salvaguarda). Así como la carpeta del Comité de control y desempeño institucional, órgano colegiado que contribuye al cumplimiento de los objetivos y metas institucionales con enfoque a resultados.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 90, 'cat_series_id' => 79, 'description' => 'Seguimiento y cumplimiento a las gestiones y recomendaciones derivadas de las auditorías, revisiones o visitas de inspección, sobre las acciones de mejora propuestas por el Órgano Interno de Control u otra instancia fiscalizadora o auditora. Así como el seguimiento a la aplicación de medidas o sanciones derivadas de las responsabilidades, inconformidades e inhabilitaciones a los servidores públicos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 91, 'cat_series_id' => 80, 'description' => 'Acta entrega-recepción de los asuntos a cargo, a la siguiente administración, a fin de aportarle información estratégica sobre los resultados y logros alcanzados por la entidad, así como las acciones, actividades y asuntos pendientes o en proceso de atención al cierre de la gestión, y asegurar con ello la consecución de los objetivos y metas en proceso de realización, así como la optimización de los recursos financieros, humanos y materiales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 92, 'cat_series_id' => 81, 'description' => 'Informe de rendición de cuentas al término de cada administración gubernamental.
            Libros Blancos en el que se hace constar, documental y narrativamente, la situación que guarde un programa, proyecto o política pública, relevante de la Administración Pública Federal.
            Memorias Documentales con la recopilación documental y descripción de las principales acciones legales, presupuestarias, administrativas, operativas, de seguimiento y de resultados obtenidos, de un programa, proyecto o política pública de la Administración Pública Federal que se hayan concluido, sobre las cuales se tiene interés en dejar constancia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 93, 'cat_series_id' => 82, 'description' => 'Seguimiento y clasificación de las Reuniones convocadas por el Presidente de la República ante diversos eventos oficiales en materia de política exterior. Registro de Acuerdos con el Titular de la SRE y Subsecretarios.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 94, 'cat_series_id' => 82, 'description' => 'Elaboración de estudios de análisis para determinar los resultados de los programas presupuestarios de la Dependencia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 95, 'cat_series_id' => 83, 'description' => 'Integración de informes y evidencias de la gestión y del estado que guarda la Secretaría en el desarrollo de sus funciones para respaldar con evidencia el Informe de Labores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 96, 'cat_series_id' => 84, 'description' => 'Sesiones ordinarias y extraordinarias del Comité de Transparencia (órgano colegiado integrado por el Titular de la Unidad de Transparencia, el Titular de la Dirección General del Acervo Histórico Diplomático, en su carácter de responsable del Área Coordinadora de Archivos, y el Titular del Órgano Interno de Control en la Secretaría de Relaciones Exteriores), para asegurar la mayor eficiencia en la gestión de las solicitudes de acceso a la información; confirmar, modificar o revocar la clasificación de la información y declaración de inexistencia o de incompetencia realicen los titulares de las áreas administrativas de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 97, 'cat_series_id' => 85, 'description' => 'Gestiones para garantizar las medidas y condiciones de accesibilidad para que toda persona pueda ejercer el derecho de acceso a la información, a través de la recepción, registro, trámite y notificación de las respuestas a las solicitudes de acceso a la información.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 98, 'cat_series_id' => 86, 'description' => 'Gestiones para publicar en la herramienta informática denominada SIPOT (Sistema de Portales de Obligaciones de Transparencia), a través de la cual los sujetos obligados de los tres niveles de gobierno, ponen a disposición de los particulares la información referente a las obligaciones de transparencia establecidas en la Ley General de Transparencia y Acceso a la Información Pública, la Ley Federal de Transparencia y Acceso a la Información Pública y las leyes locales en la materia aplicables a esta Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 99, 'cat_series_id' => 87, 'description' => 'Gestiones para garantizar que los datos personales que se reciban con motivo o en ejercicio de las funciones, sean protegidos, tratados, difundidos, transmitidos y distribuidos conforme a las disposiciones aplicables; y le confiere al individuo la facultad de acceder, rectificar, cancelar y oponerse al tratamiento de sus datos personales que sobre su persona obran en poder de esta Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 100, 'cat_series_id' => 88, 'description' => 'Disposiciones en materia de política exterior de México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 101, 'cat_series_id' => 89, 'description' => 'Planeación, diseño, ejecución y evaluación de los programas de acción internacional, específicos para los países y organizaciones de la región, así como para la región en su conjunto, a corto, mediano y largo plazo, basándose en los lineamientos generales de política exterior. 
            Gestión de las actividades necesarias para alcanzar los objetivos que persiguen las visitas del C. Presidente de la Republica y/o altos funcionarios a los países de la región, así como de sus homólogos a México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 102, 'cat_series_id' => 89, 'description' => 'Información relativa a la participación en la coordinación de las o visitas de estado, oficiales y de trabajo del Presidente de la República y los del Secretario de SRE al extranjero, así como en aquellos eventos internacionales que se realicen en México y donde también participen; así mismo en la elaboración de visitas oficiales y de trabajo a México de los jefes de Estado y de Gobierno y los titulares de Relaciones Exteriores de otros países. Instrumentación de lineamientos protocolarios aplicables a las particularidades de las visitas de Estado y de Gobierno.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 103, 'cat_series_id' => 90, 'description' => 'Informes políticos. Desarrollo de mecanismos de diálogo político y mecanismos de diálogo institucionalizados.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 104, 'cat_series_id' => 90, 'description' => 'Informes políticos: recopilación y análisis de información sobre la situación interna y posición internacional de los países de la región.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 105, 'cat_series_id' => 90, 'description' => 'Convenios, acuerdos y contratos celebrados por México con los países de la región. Programas de acción internacional con los países y organizaciones de la región.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 106, 'cat_series_id' => 91, 'description' => 'Celebración, modificación, terminación o denuncia en toda clase de tratados, acuerdos y convenciones internacionales, a fin de coadyuvar en la conducción de la política exterior, la cooperación y la promoción del país. Medidas conducentes para el cumplimiento de la Ley sobre la Celebración de Tratados, Registro de los tratados internacionales celebrados por México, así como de sus modificaciones, terminaciones o denuncias. Interpretaciones de los tratados de los México sea parte, ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 107, 'cat_series_id' => 92, 'description' => 'Propuestas para la adecuada participación de México en los foros internacionales correspondientes y en las conferencias sobre codificación y desarrollo progresivo del derecho internacional público y privado, así como formular y coordinar con las unidades administrativas competentes, tanto de la Secretaria, como de otras dependencias y entidades de la Administración Pública Federal, las posiciones sobre asuntos jurídicos que regirán la participación de México en dichos foros.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 108, 'cat_series_id' => 92, 'description' => 'Información relativa al seguimiento a las reuniones que en materia de consultas políticas gubernamentales y reuniones binacionales se realicen con los países y organizaciones de la competencia de la región, en coordinación con las unidades administrativas competentes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 109, 'cat_series_id' => 93, 'description' => 'Coordinación de la intervención y defensa del gobierno de México o de cualquiera de sus entidades en litigios o procedimientos ante tribunales extranjeros, así como representar al Estado mexicano en aquellos litigios o procedimientos ante tribunales internacionales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 110, 'cat_series_id' => 94, 'description' => 'Información derivada de las acciones para contribuir al mantenimiento de un entorno internacional estable que favorezca los intereses y objetivos nacionales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 111, 'cat_series_id' => 94, 'description' => 'Seguimiento, revisión y participación en la planeación, el diseño, la ejecución y la evaluación de los programas de acción internacional en materia de cooperación internacional de seguridad con Canadá y EUA, que incluye dialogo de alto nivel para el combate al crimen organizado transnacional, trata de personas, tráfico ilegal de armas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 112, 'cat_series_id' => 95, 'description' => 'Gestión para la recuperación de bienes arqueológicos (muebles, inmuebles, restos fósiles humanos o de la flora y la fauna), artísticos y culturales-históricos que se localicen en el extranjero y que hayan salido ilícitamente del territorio nacional.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 113, 'cat_series_id' => 95, 'description' => 'Atención de solicitudes que en materia de nacionalidad y naturalización se formulen a la Secretaria, y en su caso, expedir certificados de Carta de Naturalización, Declaratoria de Nacionalidad Mexicana por Nacimiento o Certificado de Nacionalidad Mexicana; así como imponer las sanciones a que se refiere la Ley de Nacionalidad y su Reglamento.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 114, 'cat_series_id' => 95, 'description' => 'Atención de los asuntos fronterizos entre México y EUA relativos a los límites internacionales, recursos hídricos y manejo y distribución de los recursos naturales comunes de ambos países, A través de la Comisión de Cooperación Ecológica Fronteriza (COCEF) obtener asistencia técnica a las comunidades fronterizas para la certificación de proyectos de infraestructura ambiental en esa región, y por medio del Banco de Desarrollo de América del Norte (BDAN) institución financiera binacional, obtener facilidades para el financiamiento de los proyectos certificados por la COCEF y de este modo dar seguimiento a la modernización de los Puerto Fronterizos entre México y EUA.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 115, 'cat_series_id' => 95, 'description' => 'Política, normas y acuerdos relacionados con los recursos transfronterizos del subsuelo y de los fondos marinos compartidos con naciones vecinas. Reuniones del Grupo binacional en materia de infraestructura fronteriza, Asuntos políticos bilaterales en materia de limites yaguas internacionales México - Belice, México - Cuba y México - Guatemala.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 116, 'cat_series_id' => 95, 'description' => 'Información relativa a las acciones para vigilar el cumplimiento de los tratados internacionales entre México y Estados Unidos de América, y México y Guatemala, y entre México y Belice, en materia de limites yaguas, negociar y formalizar acuerdos generados en el marco de sus atribuciones, asistir al gobierno mexicano en los asuntos que le sean encomendados, así como operar y mantener la infraestructura construida bajo dichos acuerdos, asegurando la integridad territorial y promoviendo el manejo de las cuencas transfronterizas en un marco de cooperación y transparencia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 117, 'cat_series_id' => 96, 'description' => 'Información relativa a la coordinación de las acciones que realizan las dependencias del gobierno federal con los países y organizaciones competencia de la región, en coordinación con las unidades administrativas competentes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 118, 'cat_series_id' => 97, 'description' => 'Registro histórico de las deliberaciones y acuerdos de la Comisión Consultiva de Política Exterior, en apego a los lineamientos que emita el Titular del Ramo.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 119, 'cat_series_id' => 98, 'description' => 'Información derivada de los trabajos de la Comisión y las subcomisiones del órgano colegiado encargado de conocer cualquier asunto relativo al personal del Servicio Exterior Mexicano, como: los trámites de ingreso, reincorporación, ascensos, traslados, comisiones, retiro, sanciones, solicitud de franquicias de importación y exportación de menaje de casas y vehículos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 120, 'cat_series_id' => 98, 'description' => 'Información derivada de los trámites administrativos de las Representaciones de México en el Exterior así como de las comunicaciones con la Dirección General del Servicio Exterior y de Recursos Humanos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 121, 'cat_series_id' => 98, 'description' => 'Información derivada del personal asimilado al Servicio Exterior Mexicano, que se compone de funcionarios y agregados a misiones diplomáticas y representaciones consulares, cuyo nombramiento haya sido gestionado por otra dependencia o entidad de la Administración Pública Federal u otra autoridad competente, con cargo a su propio presupuesto; por lo tanto no mantiene relación laboral con la SRE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 122, 'cat_series_id' => 99, 'description' => 'Participación en coordinación con las autoridades y unidades administrativas competentes de la Secretaría y de otras dependencias federales en el diseño e instrumentación de la política migratoria de México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 123, 'cat_series_id' => 100, 'description' => 'Programas y proyectos en materia de actuación internacional del Gobierno de la República.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 124, 'cat_series_id' => 101, 'description' => 'Opiniones sobre cuestiones de derecho del mar y derecho ambiental con base en la posición de México; coordinación de la posición nacional en organismos y foros internacionales relativos a derecho del mar y derecho ambiental con base en la opinión técnica de las otras Dependencias de la Administración Pública Federal.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 125, 'cat_series_id' => 101, 'description' => 'Información relativa a las acciones de política exterior basada en los principios constitucionales de derechos humanos y democracia. Promover la activa participación de México en la agenda internacional de derechos humanos, a través de la cooperación, además de trabajar para fortalecer los estándares internacionales de protección de los derechos humanos, la igualdad, la no discriminación y la democracia. Mantener una política de vinculación y colaboración con el sistema internacional y regional en materia de derechos humanos y democracia, de manera que sus estándares puedan impactar a nivel nacional y, contribuir así en la promoción y protección de los derechos humanos de todas las personas en México, de conformidad con la Constitución Política de los Estados Unidos y en lo que corresponde al ámbito funcional de la SRE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 126, 'cat_series_id' => 101, 'description' => 'Fortalecimiento de las relaciones comerciales, económicas y turísticas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 127, 'cat_series_id' => 101, 'description' => 'Información relativa a las Estrategias de política exterior en las instancias Internacionales para la Organización de las Naciones Unidas; participación y posición de México en las reuniones convocadas por la Organización de las Naciones Unidas y Organismos y mecanismos Internacionales Especializados; estrategias para promover iniciativas mexicanas; Candidaturas de México a los Organismos Internacionales y Candidaturas de otros países; acreditación  y actuación de las delegaciones de México  ante los órganos;   tratados, convenios y acuerdos internacionales promovidos por la Organización de las Naciones Unidas y por los Organismos y mecanismos Internacionales Especializados.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 128, 'cat_series_id' => 101, 'description' => 'Acciones encaminadas a establecer la posición de México en temas competencia de esta Dirección General, así como en aquellos otros temas emergentes de la agenda internacional y regional cuyo carácter evolutivo y dinámico exija una intervención y respuesta en beneficio de los intereses del país.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 129, 'cat_series_id' => 101, 'description' => 'Información relativa a la participación o actuación de México ante organismos y organizaciones regionales de carácter autónomo, mecanismos de concertación multilateral y mecanismos permanentes de consulta y concertación política de la región a fin de ampliar, profundizar y promover los intereses de nuestro país contenidos en su política exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 130, 'cat_series_id' => 101, 'description' => 'Documentación relativa a la coordinación de la posición oficial de México en conferencias y foros internacionales sobre la codificación y desarrollo progresivo del derecho internacional. Documentos de posición oficial, instrucciones e informe reglamentario de la participación de México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 131, 'cat_series_id' => 102, 'description' => 'Información relativa a la acreditación del Cuerpo Diplomático, Consular y funcionarios de Organismos Internacionales con Sede y Representación ante el Gobierno de México, en coordinación con las unidades administrativas competentes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 132, 'cat_series_id' => 102, 'description' => 'Gestión de la acreditación de Cónsules Honorarios de países extranjeros ante el Gobierno de México; de la acreditación de los miembros del Honorable Cuerpo Diplomático, Consular y de los Funcionarios de Organismos Internacionales, así como para renovar los documentos oficiales de manera expedita y para procesar oportunamente las solicitudes de término de comisión. Revocación de visas a los miembros del cuerpo diplomático y consular acreditado ante el gobierno de México, a petición de las representaciones extranjeras y de acuerdo con la normatividad vigente. Registro de los Jefes de Misiones Extranjeras que se ausentan del territorio nacional y de los funcionarios que permanecen como Encargados de Negocios durante el periodo provisional. Gestión del consentimiento del Estado mexicano para el establecimiento o apertura de un Consulado Honorario en una localidad de la República Mexicana, a través de su Representación Diplomática residente en México, Embajada Concurrente o Ministerio de Relaciones Exteriores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 133, 'cat_series_id' => 103, 'description' => 'Desarrollo y coordinación de los mecanismos institucionales e interinstitucionales, criterios, políticas, programas, estrategias y lineamientos encaminados a facilitar la interacción de la Secretaría con las organizaciones de la sociedad civil.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 134, 'cat_series_id' => 104, 'description' => 'Información relativa a las acciones de protocolo, ceremonial, condecoraciones, acreditaciones, privilegios e inmunidades de la diplomacia y de las demás relaciones internacionales del país o temas diplomáticos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 135, 'cat_series_id' => 105, 'description' => 'Proponer al Secretario las medidas conducentes para la adecuada participación de México en los foros internacionales correspondientes y en las conferencias sobre codificación y desarrollo progresivo del derecho internacional público y privado, así como formular y coordinar con las unidades administrativas competentes, tanto de la Secretaría, como de otras dependencias y entidades de la Administración Pública Federal, las posiciones sobre asuntos jurídicos que regirán la participación de México en dichos foros.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 136, 'cat_series_id' => 106, 'description' => 'Información relativa a las acciones en materia de programas y proyectos para cuidar el respeto a los derechos y el mejoramiento de las condiciones de vida de los mexicanos que se encuentran en el exterior, fortaleciendo la capacidad de protección, con el apoyo de las Representaciones de México en el exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 137, 'cat_series_id' => 107, 'description' => 'Información relativa a la formalización, fortalecimiento y consolidación de la red de representaciones de México en el exterior que se realicen con los países y organizaciones de la competencia de la región, en coordinación con las unidades administrativas competentes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 138, 'cat_series_id' => 107, 'description' => 'Proposición de la apertura, cierre, o redefinición de Consulados Honorarios, y sobre el Nombramiento y término de funciones de los Cónsules y Vicecónsules Honorarios de México. Elaboración las cartas patentes para el ejercicio de funciones de los Cónsules y Vicecónsules Honorarios y, en coordinación con las representaciones correspondientes, supervisar todo lo relativo al funcionamiento de dichas oficinas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 139, 'cat_series_id' => 107, 'description' => 'Apertura o reubicación de Delegaciones y Oficinas de Enlace, así como nombramientos comisión y remoción de Delegados. Coordinar la implementación de acciones que mejoren la organización y funcionamiento de las delegaciones y subdelegaciones en territorio nacional, dichas acciones, entre otras, se encuentran vinculadas con la protección a mexicanos en el exterior, asuntos jurídicos, culturales y de política exterior, con el propósito de contribuir en la generación de resultados que fortalezcan a México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 140, 'cat_series_id' => 108, 'description' => 'Coordinación con las instancias competentes, sobre las medidas de simplificación, modernización tecnológica y desregulación administrativa tendientes a mejorar la prestación de los servicios consulares y migratorios que ofrecen las representaciones de México en el exterior. Coordinación. con la Dirección General de Tecnologías de Información e Innovación, la correcta administración de los sistemas de cómputo desarrollados para los servicios consulares, a fin de facilitar la generación de información y estadísticas en la materia. Dar acceso, de conformidad con la Ley de Seguridad Nacional, a los sistemas de cómputo desarrollados para las tareas de documentación consular y, en el ámbito de su competencia, del fenómeno migratorio: así como coordinar con la Dirección General de Tecnologías de Información e Innovación, la correcta administración de los mismos, a fin de facilitar la generación de información y estadísticas en la materia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 141, 'cat_series_id' => 108, 'description' => 'Gestiones  para el  manejo  restringido  y  controlado  desde  su  producción, recolección, traslado, distribución, recepción y resguardo de las formas numeradas y/o valoradas a usar por las Representaciones de México en el Exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 142, 'cat_series_id' => 108, 'description' => 'Asesoría a las unidades administrativas, representaciones en el exterior y coordinarse con los abogados extranjeros respecto de los casos en que el Estado Mexicano deba defender los derechos humanos de sus nacionales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 143, 'cat_series_id' => 108, 'description' => 'Información relativa a las acciones para cuidar el respeto a los derechos y el mejoramiento de las condiciones de vida de los mexicanos que se encuentran en el exterior, fortaleciendo la capacidad de protección, asistencia jurídica y gestión de la Red Consular mexicana; mediante la dirección y coordinación de los casos de protección consular de la Secretaria conforme a la normatividad vigente aplicable en materia de presupuesto por las representaciones de México en el exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 144, 'cat_series_id' => 108, 'description' => 'Apoyo jurídico o asesoría a la Dirección General de Protección a Mexicanos en el Exterior y representaciones mexicanas en el exterior en relación con casos de protección a mexicanos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 145, 'cat_series_id' => 108, 'description' => 'Gestión para llevar a cabo la transferencia de recursos de connacionales derivados de los conceptos de gastos de protección consular.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 146, 'cat_series_id' => 109, 'description' => 'Atención de las peticiones de todas las Representaciones en el exterior que requieran apoyos económicos mayores a cinco mil dólares para el servicio a connacionales; autorizadas en las sesiones del Comité de Evaluación para la Asistencia a casos de Protección Consular que requieran apoyo económico mayor a cinco mil dólares.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 147, 'cat_series_id' => 110, 'description' => 'Expedición de pasaportes que es el documento de viaje que la Secretaría de Relaciones Exteriores expide a los mexicanos para acreditar su nacionalidad e identidad y solicitar a las autoridades extranjeras permitan el libre paso en ese territorio, proporcionen ayuda y protección al titular.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 148, 'cat_series_id' => 111, 'description' => 'Legalización de firmas de documentos públicos mexicanos que deban surtir efectos en el extranjero, siempre y cuando que el país en donde surtirán efectos no se encuentre adherido a la Convención de la Haya, de lo contrario el trámite que procede será el de Apostilla ante la Secretaría de Gobernación.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 149, 'cat_series_id' => 112, 'description' => 'Expedición del documento de identidad y viaje a los extranjeros que se encuentren en territorio nacional y que hubieran perdido su nacionalidad, sin haber adquirido otra y que, consecuentemente, sean considerados de nacionalidad indefinida, o que se encuentren en territorio nacional de nacionalidad definida y que no tengan representante diplomático ni consular, o que demuestren, a satisfacción de la Secretaría, que no tienen posibilidad alguna de que su representante diplomático o consular les expida pasaporte o que no tengan.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 150, 'cat_series_id' => 113, 'description' => 'Control y seguimiento de las solicitudes y consultas recibidas por parte de las Delegaciones de la Secretaría de Relaciones Exteriores y Representaciones de México en el exterior inherentes a un impedimento administrativo o judicial o algún otro servicio conforme a atribuciones..', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

        ]);
    }
}
