<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CatSamplingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_samplings')->insert([

            ['id' => 1, 'cat_series_id' => 1, 'quality' => 'Iniciativas de leyes, reglamentos, u otras normatividades.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 2, 'cat_series_id' => 2, 'quality' => 'Convenios, acuerdos y bases de coordinación y concertación.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 3, 'cat_series_id' => 6, 'quality' => 'Asesoría en materia de derecho internacional público a representaciones de México en el exterior (privilegios e inmunidades). Asesoría en materia consular y de derecho extranjero. Consultas Jurídicas en Materia Contenciosa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 4, 'cat_series_id' => 7, 'quality' => 'Juicios laborales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 5, 'cat_series_id' => 8, 'quality' => 'Juicios promovidos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 6, 'cat_series_id' => 9, 'quality' => 'Juicios de amparo.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 7, 'cat_series_id' => 11, 'quality' => 'Manuales de organización específicos por Unidades Administrativas, manuales de organización tipo para Representaciones de México en el exterior (RME) y Delegaciones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 8, 'cat_series_id' => 12, 'quality' => 'Manuales, normas y lineamientos de procedimientos internos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 9, 'cat_series_id' => 14, 'quality' => 'Programación del presupuesto.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 10, 'cat_series_id' => 17, 'quality' => 'Clima organizacional, Perspectiva de género, etc.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 11, 'cat_series_id' => 18, 'quality' => 'Todos los expedientes de personal del Servicio Exterior Mexicano; expedientes significativos del resto del personal.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 12, 'cat_series_id' => 19, 'quality' => 'Refrendo de estructura orgánica y ocupacional; descripción y perfil de puestos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 13, 'cat_series_id' => 20, 'quality' => 'Concentrados anuales de la nómina.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 14, 'cat_series_id' => 22, 'quality' => 'Reportes mensuales de incidencias y documentos generados durante el proceso.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 15, 'cat_series_id' => 23, 'quality' => 'Convocatorias a estímulo y recompensas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 16, 'cat_series_id' => 24, 'quality' => 'Trámites ante el ISSSTE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 17, 'cat_series_id' => 25, 'quality' => 'Aportaciones correspondientes al Fondo de Ahorro Capitalizable de los Trabajadores al Servicio del Estado (FONAC).', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 18, 'cat_series_id' => 26, 'quality' => 'Trabajo y conflicto. Organización. Interior y Asuntos Foráneos. Evaluación escalonaría. Finanzas. Previsión Social. Actividades Deportivas. Actividades Culturales. Estadísticas. Vivienda. Relaciones Públicas y Acción Femenil. Capacitación Sindical y para pensionados y jubilados. Actas y Acuerdos. Comisión Mixta de Escalafón. Condiciones Generales de Trabajo en la Secretaría de Relaciones Exteriores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 19, 'cat_series_id' => 27, 'quality' => 'Programas de Prevención de Riesgos de Trabajo.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 20, 'cat_series_id' => 30, 'quality' => 'Carpetas del Comité de ética y de prevención de conflictos de interés.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 21, 'cat_series_id' => 33, 'quality' => 'Conservación de Libros de mayor, libros de inventarios y balances. Eliminación de Libros de diario. Conforme a la Norma de Archivo Contable Gubernamental NACG.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 22, 'cat_series_id' => 42, 'quality' => 'Carpetas de Licitación; de Invitación a 3 personas; de Adjudicación directa.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 23, 'cat_series_id' => 43, 'quality' => 'Seguimiento a contratos y pedidos. Registros de empleados local y/o prestador de servicios profesionales independientes en las Representaciones de México en el exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 24, 'cat_series_id' => 44, 'quality' => 'Seguimiento a seguros y fianzas derivados de contratos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 25, 'cat_series_id' => 45, 'quality' => 'Seguimiento a las acciones de conservación y mantenimiento de la infraestructura física.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 26, 'cat_series_id' => 48, 'quality' => 'Inventario físico de bienes muebles y/o activo fijo. Control del patrimonio artístico.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 27, 'cat_series_id' => 49, 'quality' => 'Inventario físico (padrón) de bienes inmuebles. Control del patrimonio artístico de la SRE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 28, 'cat_series_id' => 51, 'quality' => 'Control y seguimiento de obras y remodelaciones de infraestructura.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 29, 'cat_series_id' => 52, 'quality' => 'Carpetas de Comités y subcomités de adquisiciones.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 30, 'cat_series_id' => 53, 'quality' => 'Carpetas del Comité de bienes muebles e inmuebles.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 31, 'cat_series_id' => 54, 'quality' => 'Control y seguimiento de obra pública.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 32, 'cat_series_id' => 58, 'quality' => 'Expediente individual del vehículo.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 33, 'cat_series_id' => 61, 'quality' => 'Planes, protocolos o acciones de protección civil.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 34, 'cat_series_id' => 65, 'quality' => 'Mecanismos para la administración de la seguridad de la información.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 35, 'cat_series_id' => 67, 'quality' => 'Formalización del Sistema Institucional de Archivos. Plan Anual de Desarrollo Archivístico. Instrumentos archivísticos de control y consulta. Control sistemático de la organización documental. Control de préstamos y consultas documentales. Gestión de disposición final documental. Planes de descripción de documentos históricos. Restauración y conservación documental. Acciones para la automatización de la gestión documental.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 36, 'cat_series_id' => 72, 'quality' => 'Programas de Comunicación social de la Secretaría enfocadas a la política exterior mexicana.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 37, 'cat_series_id' => 73, 'quality' => 'Máster de videos generados de productos terminados para los eventos más significativos del quehacer institucional.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 38, 'cat_series_id' => 74, 'quality' => 'Programas de difusión para fortalecer la imagen de México y de la Secretaría.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 39, 'cat_series_id' => 75, 'quality' => 'Comunicados oficiales de la SRE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 40, 'cat_series_id' => 76, 'quality' => 'Análisis y evaluación de información concerniente a México originada en medios de comunicación nacionales e internacionales. Análisis de la evaluación de desempeño de la Secretaría en medios de comunicación internacionales. Información sobre eventos actuales en medios de comunicación, nacionales e internacionales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 41, 'cat_series_id' => 77, 'quality' => 'Comparecencia en materia de Política exterior ante la Cámara de Diputados y la Cámara de Senadores.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 42, 'cat_series_id' => 79, 'quality' => 'Seguimiento de auditorías integrales realizadas a la SRE, ya sea por autoridades externas o por el Órgano Interno de Control, que hayan causado impacto en las atribuciones de la SRE.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 43, 'cat_series_id' => 80, 'quality' => 'Carpetas de Entrega–recepción que informan el estatus de los asuntos institucionales por inicio o conclusión de encargo de los servidores públicos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 44, 'cat_series_id' => 81, 'quality' => 'Informe de rendición de cuentas al término de cada administración gubernamental. Libros Blancos y/o Memorias Documentales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 45, 'cat_series_id' => 82, 'quality' => 'Reuniones convocadas por el Presidente de la República. Acuerdos con el Titular de la SRE. Informe político. Recopilación y Análisis de Información sobre la situación interna y posición internacional de los países de la región.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 46, 'cat_series_id' => 84, 'quality' => 'Carpetas de sesiones del Comité.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 47, 'cat_series_id' => 85, 'quality' => 'Impugnaciones a la respuesta proporcionada por la Dependencia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 48, 'cat_series_id' => 86, 'quality' => 'Asignación y confirmación de obligaciones de transparencia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 49, 'cat_series_id' => 87, 'quality' => 'Impugnaciones a la respuesta proporcionada por la Dependencia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 50, 'cat_series_id' => 89, 'quality' => 'Visitas del Presidente de México a países de la región. Visitas de Estado a México. Visitas de Funcionarios de Alto Nivel.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 51, 'cat_series_id' => 90, 'quality' => 'Convenios, acuerdos y contratos celebrados por México con los países de la región. Programas de acción internacional con los países y organizaciones de la región.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 52, 'cat_series_id' => 92, 'quality' => 'Conservar lo relacionado a la Asamblea de Estados Partes de la Corte Penal Internacional.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 53, 'cat_series_id' => 93, 'quality' => 'Casos Mexicanos ante mecanismos Internacionales de Derechos Humanos. Casos en la Corte Internacional de Justicia. Casos en la Corte Permanente de Arbitraje.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 54, 'cat_series_id' => 94, 'quality' => 'Incidentes y conflictos internacionales. Mecanismos de consulta y diálogo sobre temas de seguridad.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 55, 'cat_series_id' => 95, 'quality' => 'Recuperación de bienes arqueológicos, artísticos y culturales-históricos. Carta de Naturalización. Declaratoria de Nacionalidad Mexicana por Nacimiento. Certificado de Nacionalidad Mexicana. Límites y aguas. Puertos fronterizos e infraestructura. Asuntos políticos bilaterales en materia, de límites y aguas Internacionales, México-Belice y México-Guatemala. Demarcación fronteriza. Distribución de aguas internacionales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 56, 'cat_series_id' => 96, 'quality' => 'Gestiones de apoyo a otras dependencias para actividades con países de la región.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 57, 'cat_series_id' => 96, 'quality' => 'Acreditaciones de funcionarios y personal administrativo adscrito a las representaciones diplomáticas extranjeras y organismos Internacionales acreditados en México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 58, 'cat_series_id' => 97, 'quality' => 'Carpeta de la Comisión Consultiva de Política Exterior.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 59, 'cat_series_id' => 98, 'quality' => 'Sesiones del Comité, ayuda de renta, de educación, encargadurías, licencias médicas, periodos vacacionales, pasajes por vacaciones, radicación de recursos, seguros de vida y de gastos médicos, expedición de pasaporte diplomático para asimilados y sus familias, notas de estilo, movimientos de alta, baja, jubilación y actualización laboral ante el ISSSTE, cuadros de comisión, franquicias para importar menaje de casa, importación temporal, definitiva y libre de vehículos, notificaciones de arribo y validación de pasajes por traslado para dependientes económicos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 60, 'cat_series_id' => 100, 'quality' => 'Programas y proyectos de política exterior de México.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 61, 'cat_series_id' => 101, 'quality' => 'Acuerdos y acciones de cooperación en materia de derechos humanos y democracia ante organismos, instituciones y organizaciones nacionales, regionales e internacionales. Resoluciones sobre derechos humanos de los migrantes. Informes del gobierno de México conforme a los compromisos internacionales en materia de derechos humanos y democracia. Órganos de supervisión de tratados. Instrumentación de la acción internacional de México en los temas relativos a la promoción y protección de los derechos humanos, de la democracia, la promoción de la equidad de género, la lucha contra la discriminación y la atención a grupos vulnerables. Comisión para la condición jurídica y social de la mujer. Participación de México en las reuniones convocadas por organismos internacionales en Materia de derechos humanos y democracia. Migración internacional. Protección internacional. Promoción y difusión en materia de derechos humanos y democracia.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 62, 'cat_series_id' => 101, 'quality' => 'Gestiones para el fortalecimiento de las relaciones comerciales, económicas y turísticas.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 63, 'cat_series_id' => 101, 'quality' => 'Coordinación de la actuación de México ante foros internacionales. Candidaturas de México a los Organismos Internacionales. Organismos y Mecanismos Internacionales Especializados. Lineamientos, documento de posición e informe del plenario de la delegación de México que participó en la Asamblea General de la ONU.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 64, 'cat_series_id' => 102, 'quality' => 'Acreditaciones de funcionarios y personal administrativo adscrito a las representaciones diplomáticas extranjeras y organismos Internacionales acreditados en México. Acreditación y Exequátur de Cónsules Honorarios y para Cónsules Generales Acreditados en México. Revocación de visas del Cuerpo Diplomático y Consular extranjero en México. Registro de precedencia y registro de ausencias de Jefes de Misiones Extranjeras (H. Cuerpo Diplomático). Apertura de Consulados Honorarios. Beneplácitos de Embajadores extranjeros.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 65, 'cat_series_id' => 103, 'quality' => 'Mecanismos institucionales e interinstitucionales encaminados a facilitar la interacción de la Secretaría con las organizaciones de la sociedad civil.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 66, 'cat_series_id' => 104, 'quality' => 'Otorgamiento de Condecoraciones de la Orden Mexicana del Águila Azteca a Extranjeros y otorgamiento de Condecoraciones de Países Extranjeros a los Presidentes de los Estados Unidos Mexicanos.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 67, 'cat_series_id' => 105, 'quality' => 'Lineamientos u opiniones jurídicas que regirán la posición de México ante la Asamblea de los Estados Partes del Estatuto de Roma de la Corte Penal Internacional y entregar la posición de México sobre tribunales penales internacionales en foros internacionales.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 68, 'cat_series_id' => 106, 'quality' => 'Programas de trabajo en materia de protección consular. Proyectos de mejora para la protección consular.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 69, 'cat_series_id' => 107, 'quality' => 'Apertura o cierre de Embajadas. Apertura, cierre o redefinición de Consulados Honorarios. Apertura o cierre de Misiones de México en el exterior. Control de los Programas de Consulados móviles, Sobre ruedas y Jornadas sabatinas, dominicales o en días inhábiles. Apertura, modificación o reubicación y cierre de una Delegación, Subdelegación u Oficina de Enlace estatal o local. Evaluaciones sobre la aplicación de las instrucciones transmitidas a las misiones diplomáticas de México en el exterior. ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 70, 'cat_series_id' => 108, 'quality' => 'Libros del Registro Civil “tercer tanto” se debe conservar de forma permanente en la Representación. Controles por anomalías o quejas relativas a la expedición de pasaportes y matrículas. Casos de pasaportes extraviados. Registro de arraigos y de impedimentos administrativos que restrinjan la expedición de pasaportes por causas justificadas. Documentación respaldada en el SIAC-MCAS/PE Matrículas Consulares de Alta Seguridad y Pasaportes Tipo E, SIAC-SETRAM Sistema de documentación Migratoria Consulados, SIAC-SIDOMI Sistema de documentación Migratoria Consulados, SIAC-SERC Sistema Estadístico de Registro Consular, Sistema de Registro para Mexicanos en el Exterior (SIRME), Sistema de Emisión del Pasaporte Mexicano (SEPM), Sistema Integral de Trámites de Nacionalidad y Naturalización (SINNA).', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 71, 'cat_series_id' => 110, 'quality' => 'Reporte concentrado de la expedición de pasaportes diplomáticos, oficiales y ordinarios.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 72, 'cat_series_id' => 111, 'quality' => 'Expediente de la legalización de firmas de documentos públicos mexicanos con efectos en el extranjero.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 73, 'cat_series_id' => 112, 'quality' => 'Casos correspondientes a extranjeros con calidad de refugiados (Formato OP/9).', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 74, 'cat_series_id' => 113, 'quality' => 'Registro y control de impedimentos administrativos y judiciales. Expedientes.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

        ]);

    }
}
