<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CatSamplingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_samplings')->insert([

            ['id' => 1, 'cat_series_id' => 1, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Iniciativas de leyes, reglamentos, u otras normatividades.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 2, 'cat_series_id' => 2, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Convenios, acuerdos y bases de coordinación y concertación.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 3, 'cat_series_id' => 6, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Asesoría en materia de derecho internacional público a representaciones de México en el exterior (privilegios e inmunidades). Asesoría en materia consular y de derecho extranjero. Consultas Jurídicas en Materia Contenciosa.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 4, 'cat_series_id' => 7, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Juicios laborales.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 5, 'cat_series_id' => 8, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Juicios promovidos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 6, 'cat_series_id' => 9, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Juicios de amparo.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 7, 'cat_series_id' => 11, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Manuales de organización específicos por Unidades Administrativas, manuales de organización tipo para Representaciones de México en el exterior (RME) y Delegaciones.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 8, 'cat_series_id' => 12, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Manuales, normas y lineamientos de procedimientos internos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 9, 'cat_series_id' => 14, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Programación del presupuesto.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 10, 'cat_series_id' => 17, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Clima organizacional, Perspectiva de género, etc.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 11, 'cat_series_id' => 18, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Todos los expedientes de personal del Servicio Exterior Mexicano; expedientes significativos del resto del personal.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 12, 'cat_series_id' => 19, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Refrendo de estructura orgánica y ocupacional; descripción y perfil de puestos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 13, 'cat_series_id' => 20, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Concentrados anuales de la nómina.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 14, 'cat_series_id' => 22, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Reportes mensuales de incidencias y documentos generados durante el proceso.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 15, 'cat_series_id' => 23, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Convocatorias a estímulo y recompensas.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 16, 'cat_series_id' => 24, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Trámites ante el ISSSTE.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 17, 'cat_series_id' => 25, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Aportaciones correspondientes al Fondo de Ahorro Capitalizable de los Trabajadores al Servicio del Estado (FONAC).</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 18, 'cat_series_id' => 26, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Trabajo y conflicto. Organización. Interior y Asuntos Foráneos. Evaluación escalonaría. Finanzas. Previsión Social. Actividades Deportivas. Actividades Culturales. Estadísticas. Vivienda. Relaciones Públicas y Acción Femenil. Capacitación Sindical y para pensionados y jubilados. Actas y Acuerdos. Comisión Mixta de Escalafón. Condiciones Generales de Trabajo en la Secretaría de Relaciones Exteriores.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 19, 'cat_series_id' => 27, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Programas de Prevención de Riesgos de Trabajo.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 20, 'cat_series_id' => 30, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpetas del Comité de ética y de prevención de conflictos de interés.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 21, 'cat_series_id' => 33, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Conservación de Libros de mayor, libros de inventarios y balances. Eliminación de Libros de diario. Conforme a la Norma de Archivo Contable Gubernamental NACG.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 22, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpetas de Licitación; de Invitación a 3 personas; de Adjudicación directa.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 23, 'cat_series_id' => 43, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Seguimiento a contratos y pedidos. Registros de empleados local y/o prestador de servicios profesionales independientes en las Representaciones de México en el exterior.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 24, 'cat_series_id' => 44, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Seguimiento a seguros y fianzas derivados de contratos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 25, 'cat_series_id' => 45, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Seguimiento a las acciones de conservación y mantenimiento de la infraestructura física.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 26, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Inventario físico de bienes muebles y/o activo fijo. Control del patrimonio artístico.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 27, 'cat_series_id' => 49, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Inventario físico (padrón) de bienes inmuebles. Control del patrimonio artístico de la SRE.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 28, 'cat_series_id' => 51, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Control y seguimiento de obras y remodelaciones de infraestructura.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 29, 'cat_series_id' => 52, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpetas de Comités y subcomités de adquisiciones.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 30, 'cat_series_id' => 53, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpetas del Comité de bienes muebles e inmuebles.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 31, 'cat_series_id' => 54, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Control y seguimiento de obra pública.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 32, 'cat_series_id' => 58, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Expediente individual del vehículo.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 33, 'cat_series_id' => 61, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Planes, protocolos o acciones de protección civil.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 34, 'cat_series_id' => 65, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Mecanismos para la administración de la seguridad de la información.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 35, 'cat_series_id' => 67, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Formalización del Sistema Institucional de Archivos. Plan Anual de Desarrollo Archivístico. Instrumentos archivísticos de control y consulta. Control sistemático de la organización documental. Control de préstamos y consultas documentales. Gestión de disposición final documental. Planes de descripción de documentos históricos. Restauración y conservación documental. Acciones para la automatización de la gestión documental.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 36, 'cat_series_id' => 72, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Programas de Comunicación social de la Secretaría enfocadas a la política exterior mexicana.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 37, 'cat_series_id' => 73, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Máster de videos generados de productos terminados para los eventos más significativos del quehacer institucional.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 38, 'cat_series_id' => 74, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Programas de difusión para fortalecer la imagen de México y de la Secretaría.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 39, 'cat_series_id' => 75, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Comunicados oficiales de la SRE.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 40, 'cat_series_id' => 76, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Análisis y evaluación de información concerniente a México originada en medios de comunicación nacionales e internacionales. Análisis de la evaluación de desempeño de la Secretaría en medios de comunicación internacionales. Información sobre eventos actuales en medios de comunicación, nacionales e internacionales.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 41, 'cat_series_id' => 77, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Comparecencia en materia de Política exterior ante la Cámara de Diputados y la Cámara de Senadores.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 42, 'cat_series_id' => 79, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Seguimiento de auditorías integrales realizadas a la SRE, ya sea por autoridades externas o por el Órgano Interno de Control, que hayan causado impacto en las atribuciones de la SRE.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 43, 'cat_series_id' => 80, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpetas de Entrega–recepción que informan el estatus de los asuntos institucionales por inicio o conclusión de encargo de los servidores públicos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 44, 'cat_series_id' => 81, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Informe de rendición de cuentas al término de cada administración gubernamental. Libros Blancos y/o Memorias Documentales.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 45, 'cat_series_id' => 82, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Reuniones convocadas por el Presidente de la República. Acuerdos con el Titular de la SRE. Informe político. Recopilación y Análisis de Información sobre la situación interna y posición internacional de los países de la región.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 46, 'cat_series_id' => 84, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpetas de sesiones del Comité.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 47, 'cat_series_id' => 85, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Impugnaciones a la respuesta proporcionada por la Dependencia.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 48, 'cat_series_id' => 86, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Asignación y confirmación de obligaciones de transparencia.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 49, 'cat_series_id' => 87, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Impugnaciones a la respuesta proporcionada por la Dependencia.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 50, 'cat_series_id' => 89, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Visitas del Presidente de México a países de la región. Visitas de Estado a México. Visitas de Funcionarios de Alto Nivel.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 51, 'cat_series_id' => 90, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Convenios, acuerdos y contratos celebrados por México con los países de la región. Programas de acción internacional con los países y organizaciones de la región.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 52, 'cat_series_id' => 92, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Conservar lo relacionado a la Asamblea de Estados Partes de la Corte Penal Internacional.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 53, 'cat_series_id' => 93, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Casos Mexicanos ante mecanismos Internacionales de Derechos Humanos. Casos en la Corte Internacional de Justicia. Casos en la Corte Permanente de Arbitraje.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 54, 'cat_series_id' => 94, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Incidentes y conflictos internacionales. Mecanismos de consulta y diálogo sobre temas de seguridad.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 55, 'cat_series_id' => 95, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Recuperación de bienes arqueológicos, artísticos y culturales-históricos. Carta de Naturalización. Declaratoria de Nacionalidad Mexicana por Nacimiento. Certificado de Nacionalidad Mexicana. Límites y aguas. Puertos fronterizos e infraestructura. Asuntos políticos bilaterales en materia, de límites y aguas Internacionales, México-Belice y México-Guatemala. Demarcación fronteriza. Distribución de aguas internacionales.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 56, 'cat_series_id' => 96, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Gestiones de apoyo a otras dependencias para actividades con países de la región.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 57, 'cat_series_id' => 96, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Acreditaciones de funcionarios y personal administrativo adscrito a las representaciones diplomáticas extranjeras y organismos Internacionales acreditados en México.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 58, 'cat_series_id' => 97, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Carpeta de la Comisión Consultiva de Política Exterior.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 59, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Sesiones del Comité, ayuda de renta, de educación, encargadurías, licencias médicas, periodos vacacionales, pasajes por vacaciones, radicación de recursos, seguros de vida y de gastos médicos, expedición de pasaporte diplomático para asimilados y sus familias, notas de estilo, movimientos de alta, baja, jubilación y actualización laboral ante el ISSSTE, cuadros de comisión, franquicias para importar menaje de casa, importación temporal, definitiva y libre de vehículos, notificaciones de arribo y validación de pasajes por traslado para dependientes económicos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 60, 'cat_series_id' => 100, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Programas y proyectos de política exterior de México.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 61, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Acuerdos y acciones de cooperación en materia de derechos humanos y democracia ante organismos, instituciones y organizaciones nacionales, regionales e internacionales. Resoluciones sobre derechos humanos de los migrantes. Informes del gobierno de México conforme a los compromisos internacionales en materia de derechos humanos y democracia. Órganos de supervisión de tratados. Instrumentación de la acción internacional de México en los temas relativos a la promoción y protección de los derechos humanos, de la democracia, la promoción de la equidad de género, la lucha contra la discriminación y la atención a grupos vulnerables. Comisión para la condición jurídica y social de la mujer. Participación de México en las reuniones convocadas por organismos internacionales en Materia de derechos humanos y democracia. Migración internacional. Protección internacional. Promoción y difusión en materia de derechos humanos y democracia.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 62, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Gestiones para el fortalecimiento de las relaciones comerciales, económicas y turísticas.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 63, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Coordinación de la actuación de México ante foros internacionales. Candidaturas de México a los Organismos Internacionales. Organismos y Mecanismos Internacionales Especializados. Lineamientos, documento de posición e informe del plenario de la delegación de México que participó en la Asamblea General de la ONU.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 64, 'cat_series_id' => 102, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Acreditaciones de funcionarios y personal administrativo adscrito a las representaciones diplomáticas extranjeras y organismos Internacionales acreditados en México. Acreditación y Exequátur de Cónsules Honorarios y para Cónsules Generales Acreditados en México. Revocación de visas del Cuerpo Diplomático y Consular extranjero en México. Registro de precedencia y registro de ausencias de Jefes de Misiones Extranjeras (H. Cuerpo Diplomático). Apertura de Consulados Honorarios. Beneplácitos de Embajadores extranjeros.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 65, 'cat_series_id' => 103, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Mecanismos institucionales e interinstitucionales encaminados a facilitar la interacción de la Secretaría con las organizaciones de la sociedad civil.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 66, 'cat_series_id' => 104, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Otorgamiento de Condecoraciones de la Orden Mexicana del Águila Azteca a Extranjeros y otorgamiento de Condecoraciones de Países Extranjeros a los Presidentes de los Estados Unidos Mexicanos.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 67, 'cat_series_id' => 105, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Lineamientos u opiniones jurídicas que regirán la posición de México ante la Asamblea de los Estados Partes del Estatuto de Roma de la Corte Penal Internacional y entregar la posición de México sobre tribunales penales internacionales en foros internacionales.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 68, 'cat_series_id' => 106, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Programas de trabajo en materia de protección consular. Proyectos de mejora para la protección consular.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 69, 'cat_series_id' => 107, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Apertura o cierre de Embajadas. Apertura, cierre o redefinición de Consulados Honorarios. Apertura o cierre de Misiones de México en el exterior. Control de los Programas de Consulados móviles, Sobre ruedas y Jornadas sabatinas, dominicales o en días inhábiles. Apertura, modificación o reubicación y cierre de una Delegación, Subdelegación u Oficina de Enlace estatal o local. Evaluaciones sobre la aplicación de las instrucciones transmitidas a las misiones diplomáticas de México en el exterior.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 70, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Libros del Registro Civil “tercer tanto” se debe conservar de forma permanente en la Representación. Controles por anomalías o quejas relativas a la expedición de pasaportes y matrículas. Casos de pasaportes extraviados. Registro de arraigos y de impedimentos administrativos que restrinjan la expedición de pasaportes por causas justificadas. Documentación respaldada en el SIAC-MCAS/PE Matrículas Consulares de Alta Seguridad y Pasaportes Tipo E, SIAC-SETRAM Sistema de documentación Migratoria Consulados, SIAC-SIDOMI Sistema de documentación Migratoria Consulados, SIAC-SERC Sistema Estadístico de Registro Consular, Sistema de Registro para Mexicanos en el Exterior (SIRME), Sistema de Emisión del Pasaporte Mexicano (SEPM), Sistema Integral de Trámites de Nacionalidad y Naturalización (SINNA).</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 71, 'cat_series_id' => 110, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Reporte concentrado de la expedición de pasaportes diplomáticos, oficiales y ordinarios.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 72, 'cat_series_id' => 111, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Expediente de la legalización de firmas de documentos públicos mexicanos con efectos en el extranjero.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 73, 'cat_series_id' => 112, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Casos correspondientes a extranjeros con calidad de refugiados (Formato OP/9).</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 74, 'cat_series_id' => 113, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Registro y control de impedimentos administrativos y judiciales. Expedientes.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],

            ['id' => 75, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Informes, registros, correos electrónicos, notas informativas relativos a trámites administrativos de las Representaciones de México en el Exterior.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 76, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Expediente del personal asimilado al Servicio Exterior Mexicano.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 77, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Protección consular y asistencia en el Exterior. Pena de muerte. Notificación Consular.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['id' => 78, 'cat_series_id' => null, 'quality' => '<p style="font-family: Montserrat; font-size: 14px; font-style: normal; font-weight: normal;">Casos de: Derechos Humanos, Penal, Migratorio, Laboral, Civil, Administrativo, respaldados en el Sistema Integral de Protección Consular (SIPC), así como los reportes generales que arroja dicho sistema.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
        ]);

    }
}
